### PR TITLE
Copying all upgrade docs over to Konvoy

### PR DESCRIPTION
**Pull request by gvasquezvargas**
## Jira Ticket
https://jira.d2iq.com/browse/D2IQ-87098

## Description of changes being made
Copied all upgrade docs over to Konvoy and updated the relative links, so they work on this location as well.

## Preview
http://docs-d2iq-com-pr-4272.s3-website-us-west-2.amazonaws.com/

### CODE REVIEW

**Review by dkoshkin — COMMENTED** [review]
What do we do with the update docs https://github.com/mesosphere/dcos-docs-site/tree/main/pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/update? (similar to other providers)

Do we remove it?

**Comment by mwrightd2** [comment]
> > https://github.com/mesosphere/dcos-docs-site/tree/main/pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/update
> 
> > What do we do with the update docs https://github.com/mesosphere/dcos-docs-site/tree/main/pages/dkp/konvoy/2.2/choose-infrastructure/aws/advanced/update? (similar to other providers)
> > Do we remove it?
> 
> Good catch! I think we should, but want to get a second opinion. @mackdubya what do you think?

Yep, dump them.

**Comment by gvasquezvargas** [comment]
Dumped AWS, Azure and Pre-provisioned files (we did not seem to have update/upgrade topics for other provider). Can you please confirm and approve @mackdubya ?

**Comment by mwrightd2** [comment]
> Dumped AWS, Azure and Pre-provisioned files (we did not seem to have update/upgrade topics for other providers). Can you please confirm and approve @mackdubya ?

Correct, that was the rest of them.

**Review by mwrightd2 — APPROVED** [review]

**Pull request merged**
