### PR TITLE
Update docs on EE DC/OS 1.11 installation with a custom CA certificate

### PR DESCRIPTION
**Pull request by ahairape**
## Description
This PR updates the documentation on EE DC/OS v1.11 installation with a custom CA certificate. The update is similar to the earlier PR (https://github.com/mesosphere/dcos-docs-site/pull/385) on EE DC/OS v1.10 documentation.

https://jira.mesosphere.com/browse/DCOS-19638

## Urgency
- [ ] Blocker 
- [ X] High
- [ ] Medium

### CODE REVIEW

**Comment by jgehrcke** [comment]
> the update is similar to the earlier PR (#385) 

I expected 'equivalent'. What do I need to watch out for as a reviewer? Can I merge blindly?

**Comment by jgehrcke** [comment]
@ahairape I am merging now. Please double-check asap in the staging environment if this appears to be as expected.

**Comment by ahairape** [comment]
@jgehrcke "equivalent" is more proper word. The only difference is that the links in 1.11 version point to 1.11 documentation (naturally).
I'm checking the docs in the staging area now.

**Comment by ahairape** [comment]
@jgehrcke, the "Using Custom CA Certificate" doc looks **OK** in the staging area: http://docs-staging.mesosphere.com/1.11/security/ent/tls-ssl/ca-custom/ 
Also the Configuration Reference for the EE DC/OS v1.11 looks **OK**: http://docs-staging.mesosphere.com/1.11/installing/ent/custom/configuration/configuration-parameters/

The Configuration Reference for OSS DC/OS v1.11 has the expected content, however the **ENTERPRISE** labels are included in braces, which in **NOT OK**: http://docs-staging.mesosphere.com/1.11/installing/oss/custom/configuration/configuration-parameters/
I am checking what could cause it.

**Comment by ahairape** [comment]
Ah, I see it now, the weird braces have been there also before my changes, I haven't introduced them.
Anyway, the PR I am preparing will propose to remove those EE-specific parameters from OSS Configuration Reference: https://jira.mesosphere.com/browse/DCOS-21144

**Pull request merged**
