### PR TITLE
Clarified the docker_remove_delay flag.

### PR DESCRIPTION
**Pull request by joerg84**
## Urgency
- [ ] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects).
- Change all affected versions (e.g. 1.7, 1.8, 1.9, 1.10, 1.11).
- See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing).

### CODE REVIEW

**Comment by joerg84** [comment]
Fixes https://jira.mesosphere.com/browse/DCOS_OSS-1987

**Comment by kikicarbonell** [comment]
I review your changes but I'm not clear about the right example to setup this config variable: `docker_remove_delay` ?

**Comment by joerg84** [comment]
@kikicarbonell Is is now less confusing? The keypart is that this flag is a Mesos concept (while the enable one is influencing the systemd timer unit)

**Comment by kikicarbonell** [comment]
yes I understand now!...Not exist relation between `docker_remove_delay` and `enable_docker_gc`. Thanks for your time.

**Pull request merged**
