### PR TITLE
Release notes for 1.13.4

### PR DESCRIPTION
**Pull request by SarahStegall**
## Jira Ticket
https://jira.mesosphere.com/browse/DCOS-58337

## Description of changes being made
New release notes for DC/OS 1.13.4

### CODE REVIEW

**Comment by SarahStegall** [comment]
Local build is successful and complete.

**Comment by mzarrabi** [comment]
Looks good. Thanks.

**Comment by SarahStegall** [comment]
I put the "wip" and "Do Not Merge" labels back because we need to wait until the download site is ready. Right now any link to 1.13.4 downloads throws a 404.

**Comment by SarahStegall** [comment]
Final check of local build shows correct working link to download sites. Ready to merge.

**Pull request merged**
