### PR TITLE
removing old Kaptain doc

### PR DESCRIPTION
**Pull request by cmastr**
Signed-off-by: Casie Oxford <coxford@d2iq.com>

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-<add_pr_##_here>.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

### CODE REVIEW

**Review by cneth — COMMENTED** [review]
This looks ok, just a reminder that before you merge this one, you need to make one that adds these same files to the Archive branch....

**Comment by cmastr** [comment]
> This looks ok, just a reminder that before you merge this one, you need to make one that adds these same files to the Archive branch....

@vacas5 did that for me.

**Comment by vacas5** [comment]
@cmastr I created a tag. Did you want a PR with this merged into archive too?

**Comment by vacas5** [comment]
https://github.com/mesosphere/dcos-docs-site/pull/4484

**Review by vacas5 — APPROVED** [review]

**Review by cneth — APPROVED** [review]

**Pull request merged**
