### PR TITLE
Added CLI documentation for DC/OS 1.14.

### PR DESCRIPTION
**Pull request by ArmandGrillet**
## Jira Ticket
Before creating this pull request, please make sure you have a separate ticket for the docs team to track their work to review and merge, even for minor edits. If you need assistance, ask in the #doc-team channel on slack.

https://jira.mesosphere.com/browse/DCOS_OSS-5242

## Description of changes being made

Copy-pasted the documentation for 1.13 to a 1.14 directory and updated the command reference of dcos node log to talk about the new `--all` flag.

## Checklist
- [ ] Make sure you change all affected versions (e.g. 1.10, 1.11, 1.12, 1.13).
- [ ] Test all commands and procedures where applicable.
- [ ] Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects) if you are moving a page.

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing) for more information.

### CODE REVIEW

**Comment by ArmandGrillet** [comment]
@lsgunnlsgunn I've read the description for `--all` and approve it :+1:.

**Comment by ck4adventure** [comment]
@ArmandGrillet This PR was immediately reverted because you had cloned the entire 1.14 docs set. What section of this actually has updates relevant to the 1.14 CLI??? I can cherry pick pages and sections as needed from this code.

**Comment by ArmandGrillet** [comment]
The only addition reverted was this one: https://github.com/mesosphere/dcos-docs-site/commit/e032fd0db3df63fd63e987433bd6f5ba3df6d7c1#diff-fb1209665e51ec1f1c348c0b1b4391a4

**Comment by ck4adventure** [comment]
Thank you, I'll make sure it gets back in.

**Comment by ck4adventure** [comment]
Does that change need to get backported into the rest of the docs?? I just looked at the 1.13 page and it does not have the --all in the table either.....

**Comment by ArmandGrillet** [comment]
This doesn't need to be backported, this is a new flag that is available in the 1.14 CLI.

**Comment by ck4adventure** [comment]
The --all flag listed in the CLI docs for 1.12 and upwards, which is what prompted me to ask. This is not correct?? the --all is new for 1.14??

**Pull request merged**
