### PR TITLE
DCOS-47246 MongoDB Service Guide

### PR DESCRIPTION
**Pull request by SarahStegall**
## Description
https://jira.mesosphere.com/browse/DCOS-47246

This PR replaces https://github.com/mesosphere/dcos-docs-site/pull/1866

## Urgency
- [ ] Blocker 
- [x] High
- [ ] Medium

Reviewed and edited all docs. Changes made:

- Renamed "Authentication" folder to lower-case as per Mesosphere standards
- Restructured Security into two files: Secrets and Authentication. No content changes.
- Replaced 90% of Limitations with #include command for /include/limitations.tmpl, which was identical. I retained the last paragraph, which was unique to this service guide.

Issues remaining:

Directory name:

The directory is named "mongodb-enterprise". This is not in compliance with our standards. I want to rename it to "mongodb". Is there a compelling reason not to do so?

Quick Start Guide:

The screenshots for Ops Manager display fields with red asterisks, which usually indicate required fields. Three fields are not filled in and there is no discussion of them: "base_URL", "project_ID" and "ops username". These fields are noted as "required" under the CLI installation procedure. May I assume that they are also required for the Catalog method? Would the values for these fields be the same in both methods?

The output for the command "dcos package install mongodbservice" includes a notice of the default configuration requirements. Shouldn't this information also be called out in the Prerequisites section at the top of the page?

Release Notes:
What is the release date for these release notes?

Authentication:
In the section "Configuring MongoDB Authentication", several steps refer to "mongod" shell. Should this be "mongodb" shell instead?

### CODE REVIEW

**Comment by vibhujain** [comment]
Hi @SarahStegall ,
Thank you so much for your help and time to review the docs and edit them wherever required.
Regarding Issues:
* Directory Name - We are deploying MongoDB that includes its enterprise version features. That is why the service directory name is 'mongodb-enterprise'. This is separate from the meta-data flag for 'enterprise', as these features are not confined to the DC/OS Enterprise version. (Refer https://docs.mesosphere.com/1.12/installing/production/deploying-dcos/configuration/examples/ for more about DC/OS enterprise flag for services carrying DC/OS enterprise features)
So, the application directory name is mongodb-enterprise, but we will update the landing page specifying the enterprise features and removing 'open-source'.
• Quick Start Guide: Yes, "base_URL", "project_ID", "public_api_key" and "ops username" are the mandatory fields that are required for both CLI and Catalog method. The value for the fields will be same in either case. We have already stated these parameter values as prerequisite (https://github.com/viivek46/dcos-docs-site/blob/mongodb_service_guide/pages/services/mongodb-enterprise/0.1.0-4.0.3/quick-start-guide/index.md#prerequisites). Further, in the catalog view section of guide, we can add notes about the values of these required parameters and some demonstration about where the user can find these values, if required!
In case of default configuration requirements, these are default config values and in production configuration, they will vary as per the usage. We will update quick start guide and mention the default configuration as a prerequisite.
• Release Date - The release date is usually the date when PR is raised to get the release branch merged into the universe. Ravi can help us regarding the release date for now. @ryadav88 
• Authentication - It is actually 'mongo' shell that is an interactive JavaScript shell interface to MongoDB database. This is a typo and we will correct it wherever 'mongod' is mentioned.

Also, Please let me know in which repo these changes needs to be done so that we'll be on the same track.
CC: @viivek46 @AnandJat

**Comment by AnandJat** [comment]
Hi @SarahStegall ,
Request please go through the response of  remaining Issues by Vibhu and let us know in which branch we have do done the changes to avoid conflicts.

**Comment by SarahStegall** [comment]
Vibhu: In your response you state:

Authentication - It is actually 'mongo' shell that is an interactive JavaScript shell interface to MongoDB database. This is a typo and we will correct it wherever 'mongod' is mentioned.

Are you planning to do another pass on these documents?

**Comment by AnandJat** [comment]
Hi @SarahStegall 

Thanks for your response , actually "mongodb" is database instance and  "mongo" is the shell of that instance and use of this shell is here only to just check the connection of "mongodb" after authentication enable.

Instead of "mongo"  there was a typo error of "mongod" , so we just need to update the same at two place point number 12 and 13 on authentication page.

We just need to clear in which repository  these changes needs to be commit changes so that we'll be on the same track.

**Comment by SarahStegall** [comment]
- I am not sure this directory name is approp

**Comment by vibhujain** [comment]
Hi @SarahStegall 

Yes, we are using the enterprise version of MongoDB and hence we named the directory as 'mongodb-enterprise' to emphasize it's enterprise features. It is similar to 'Datastax Enterprise' which is named as 'dse' in service guide directory, hence we added a postfix 'enterprise' to our directory name.
We agree with your suggestions and it is fine to mention it on landing page.
cc @AnandJat

**Comment by SarahStegall** [comment]
Okay, since I can't push to your repo and you can't push to mine, I have done the following, based on the changes you did on the commit you mentioned:

Verified default system requirements added to Quick Start Guide
Verified 'enterprise' flags are now set to 'false' for Release Notes, Security, and Supported Version pages.
Added the following sentence to the landing page for the service and for this release: "This service guide is based on the MongoDB Enterprise (paid) version of MongoDB."
Verified correction of "mongod" to "mongo" in authentication page.

I will change the name of the directory to "mongodb" and merge this PR.

**Comment by vibhujain** [comment]
Thank you so much for you help @SarahStegall. For release date, we are in touch with @ryadav88 regarding our universe PR. We'll let you know about the release date once we discuss that with Ravi.
cc @AnandJat

**Comment by ck4adventure** [comment]
Update 4/17/19: continue to hold per Ravi.

**Comment by SarahStegall** [comment]
Closing PR per @ryadav88 as this is no longer under active development.

**Pull request closed without merging**
