### PR TITLE
add @theia/core v0.3.7 to the list

### PR DESCRIPTION
**Pull request by nLight**
## Description
In the dcos-ui we wrote a piece of code that derives from parts of `theia/core`.

## Urgency
- [ ] Blocker 
- [ ] High
- [x] Medium

## Requirements
- Test all commands and procedures.
- Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects).
- Change all affected versions (e.g. 1.7, 1.8, 1.9, 1.10, 1.11).
- See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing).

### CODE REVIEW

**Comment by nLight** [comment]
@pavisandhu anything I need to do to get this in?

**Comment by nLight** [comment]
@cmastr we still use the library :) and still don't have it on the list https://docs.d2iq.com/mesosphere/dcos/2.0/release-notes/open-source-attribution/

**Comment by nLight** [comment]
@orlandohohmeier 👀

**Comment by orlandohohmeier** [comment]
@cmastr what do we need to do to land this addition?

**Comment by cmastr** [comment]
Can we start a new PR for this? The change above is against Master, not Staging for one. Plus it's so old that there are merge conflicts. And we need a JIRA ticket for this as well. Seems better to start over.

**Comment by nLight** [comment]
https://github.com/mesosphere/dcos-docs-site/pull/2788

**Pull request closed without merging**
