### PR TITLE
clarify supported browser versions

### PR DESCRIPTION
**Pull request by nLight**
## Jira Ticket
Before creating this pull request, please make sure you have a separate ticket for the docs team to track their work to review and merge, even for minor edits. If you need assistance, ask in the #doc-team channel on slack.

https://jira.mesosphere.com/browse/DCOS-54113

## Checklist
- [x] Make sure you change all affected versions (e.g. 1.10, 1.11, 1.12, 1.13).
- [x] Test all commands and procedures where applicable.
- [x] Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects) if you are moving a page.

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing) for more information.

### CODE REVIEW

**Comment by nLight** [comment]
I'm not native eng speaker, please verify the wording. Thanks!

**Comment by nLight** [comment]
@cmastr this has been an issue with one of our customers already. If we don't clarify the versions we support they can ask to support outdated browsers.

**Comment by nLight** [comment]
@orlandohohmeier 👀

**Comment by cmastr** [comment]
Reopening the JIRA for this, but we need to reevaluate what we say about supported browser versions for the product. So won't reopen the PR. We'll open a new one when we're ready to update docs.

**Pull request closed without merging**
