### PR TITLE
Add Kubeflow-scaffold

### PR DESCRIPTION
**Pull request by pierrebeitz**
# ⚠️ do not merge (yet)!

### depends on https://github.com/mesosphere/dcos-docs-site/pull/2908.

review and merge https://github.com/mesosphere/dcos-docs-site/pull/2908 first. that PR is independent of kubeflow-docs. 

-------------

# Screenshot

Just a first shot on how we might want to add a new tile. I could also imagine a 3/2-layout, where 3 tiles are on the upper row and two tiles move to a second row or a layout where we present the products vertically. 

D2iQ Docs 2020-05-07 18-19-59

EDIT: there now also is a semi-functional kubeflow-section. by semi-functional i mean that a lot of layouts seem to be overly complicated and thus i'm not sure whether headers work the the way they should.

### CODE REVIEW

**Comment by danielone** [comment]
@pierrebeitz do you feel we can fit a 5th tile here without scroll on a laptop size screen? how much would the current tile size need to be reduced?

would it be possible to prototype putting the tile graphic to the left of each text block below please? this is an alt layout @cmastr and I are discussing ?

**Comment by pierrebeitz** [comment]
@danielone if you mean the horizontal scrollbar: nice catch! unfortunately it's not an issue i introduced in this PR but we also have that live. here's a fix: https://github.com/mesosphere/dcos-docs-site/pull/2914.

so the tile sizes will stay the same as in the current state of this PR. they vary between 768px and 1024px.

### min 

D2iQ Docs 2020-05-10 05-31-42


### max

D2iQ Docs 2020-05-10 05-30-12


# alternative layout prototype

i tried to do something sensible with my limited layouting-skills. i feel that this does not look right yet, but think it might be a valid option with some more of your input:

D2iQ Docs 2020-05-10 06-09-30

here's the commit in case you want to check it out and tweak stuff yourself in the `scss`-file: https://github.com/mesosphere/dcos-docs-site/commit/daada0962e55e5d6e807e6dea68ee05cfa845170

**Comment by cmastr** [comment]
> @danielone if you mean the horizontal scrollbar: nice catch! unfortunately it's not an issue i introduced in this PR but we also have that live. here's a fix: #2914.
> 
> so the tile sizes will stay the same as in the current state of this PR. they vary between a screen size of 768px and 1024px as follows:
> 
> ### min
> D2iQ Docs 2020-05-10 05-31-42
> 
> ### max
> D2iQ Docs 2020-05-10 05-30-12
> 
> # alternative layout prototype
> i tried to do something sensible with my limited layouting-skills. images are vertically centered and are hidden below laptop-size. i feel that this does not look right yet, but think it might be a valid option with some more of your input:
> 
> D2iQ Docs 2020-05-10 06-09-30
> 
> here's the commit in case you want to check it out and tweak stuff yourself in the `scss`-file: [daada09](https://github.com/mesosphere/dcos-docs-site/commit/daada0962e55e5d6e807e6dea68ee05cfa845170)

This looks pretty good! And it would save us from the space issues we may have in the future if we have additional products.

**Comment by danielone** [comment]
@pierrebeitz  thanks for trying that out!! It looks like @cmastr likes the general direction too. 
We may need to tweak the image sizing and ensure same alignment for image for each section, as well keep description text length more balanced between each but looks like we have a good path if Anne Marie also on board. 

In the tile region above, ideally we show some sort of filter to filter down the choices by sphere inspired by d2iq.com site:
https://share.getcloudapp.com/E0ubLNB1

@cmastr good to chat more about with AnneM at our meeting coming up.

**Comment by pierrebeitz** [comment]
let me know if something like a live-tweaking-session would be helpful. 

i'm on PTO next week though.

**Comment by cmastr** [comment]
Ok, so I found out yesterday that we are going to need to add Conductor soon as well. So we definitely need to go the vertical route I think. Let's not add Conductor in this PR though.

**Comment by cmastr** [comment]
Has lots of merge conflicts now and we've decided to go in another direction, so suggestion is to close this in favor of upcoming design work.

**Pull request closed without merging**
