### PR TITLE
Added line clarifying compatibility with OSS and Enterprise

### PR DESCRIPTION
**Pull request by aggress**
## Urgency
- [ ] Blocker 
- [ ] High
- [x] Medium

## Requirements
- Test all commands and procedures.
- Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects).
- Change all affected versions (e.g. 1.7, 1.8, 1.9, 1.10, 1.11, 1.12).
- See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing).

### CODE REVIEW

**Comment by aggress** [comment]
I had a customer ask today if our K8s package was compatible with OSS and it's not clear, especially as when you hit the setting up page it specifies a requirement for Enterprise, so I added a line in the top level overview to highlight it is compatible and created a PR.

**Comment by aggress** [comment]
This is for https://jira.mesosphere.com/browse/DCOS_OSS-4977?filter=-2

**Comment by ck4adventure** [comment]
May need to be a PR against K8s repo, will check.

**Comment by ck4adventure** [comment]
Closing as this has to happen on K8s, and not just one docs version.

**Pull request closed without merging**
