### PR TITLE
docs: Fixes after 2.1 to 2.2 paste

### PR DESCRIPTION
**Pull request by gracedo**
## Jira Ticket
https://jira.d2iq.com/browse/D2IQ-82714

## Description of changes being made
Went through https://github.com/mesosphere/dcos-docs-site/pull/4008 again and found a few more things to fix.

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Create new PRs against `develop`, or `main` for hotfixes to production.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

### CODE REVIEW

**Comment by gracedo** [comment]
Hmm ok I think a few of these changes on 2.1 need to be made on `main` instead, lemme rework this branch and remove those changes and move them against `main` instead.

**Comment by gracedo** [comment]
All right, moved the 2.1 changes out to https://github.com/mesosphere/dcos-docs-site/pull/4022 and removed them from this PR. The changes that go into `main` in that PR should make it back into `develop`

**Review by vacas5 — APPROVED** [review]
thanks for doing that Grace. 2.2 is where it's at

**Review by msdolbey — APPROVED** [review]
👍 
Solid - good catches
Nice

**Pull request merged**
