### PR TITLE
dcos-monitoring: Add docs for 1.4.0

### PR DESCRIPTION
**Pull request by viivek46**
https://jira.d2iq.com/browse/D2IQ-65705

### CODE REVIEW

**Comment by Poltergeist** [comment]
@cmastr I see that you added a `needs_jira` label on this PR. What do we need to do in order to remove this label? Also is that the reason for the `wip` label? Sorry for not being educated on the process.

**Comment by cmastr** [comment]
> @cmastr I see that you added a `needs_jira` label on this PR. What do we need to do in order to remove this label? Also is that the reason for the `wip` label? Sorry for not being educated on the process.

We have to have the JIRA link in the description. Please add it. If you don't have a JIRA, please create one and add the number.

**Comment by cmastr** [comment]
@Poltergeist  - WIP means that we are still working on approvals for this PR. Once you have approval from everyone in the reviewers section, we can turn this to readytomerge.

**Comment by kaiwalyajoshi** [comment]
Looks good to merge!

**Comment by viivek46** [comment]
new PR with all changes from this PR : https://github.com/mesosphere/dcos-docs-site/pull/2821

**Pull request closed without merging**
