### PR TITLE
COPS-3150 Adding disclaimer note about Ubuntu to ACS docs in 1.9, 1.1…

### PR DESCRIPTION
**Pull request by SarahStegall**
…0 and 1.11

## Description
https://jira.mesosphere.com/browse/COPS-3150

## Urgency
- [ ] Blocker 
- [x] High
- [ ] Medium

Added disclaimer note about Ubuntu to all ACS install docs in 1.9, 1.10 and 1.11.

### CODE REVIEW

**Comment by yishan-lin** [comment]
Hey Sarah, thanks for getting on this!  Looks good to me.

You're right in that we should update these 2 other pages:

- https://docs.mesosphere.com/1.11/developing-services/tunnel/#linux-openvpn-client-installation
- https://docs.mesosphere.com/1.11/administering-clusters/sshcluster/#ssh-to-your-dcos-cluster-on-unixlinux-macos-ubuntu-etc

The latter will need its hyperlink updated, although that may be fixed by revising the h1 at the top.

**Comment by SarahStegall** [comment]
Working on these suggestions, but I'm a little confused by the last sentence. What do you mean by changing "the H1 at the top"? Do you mean the page title?

**Comment by yishan-lin** [comment]
Yeah, the header at the top. :)

**Comment by SarahStegall** [comment]
Added disclaimers to 

    https://docs.mesosphere.com/1.11/developing-services/tunnel/#linux-openvpn-client-installation
    https://docs.mesosphere.com/1.11/administering-clusters/sshcluster/#ssh-to-your-dcos-cluster-on-unixlinux-macos-ubuntu-etc

No need to change any headings. :)

**Pull request merged**
