### PR TITLE
ss/DCOS-56489 Konvoy docs update

### PR DESCRIPTION
**Pull request by SarahStegall**
## Jira Ticket
https://jira.mesosphere.com/browse/DCOS-56489
## Description of changes being made
Update, edit Konvoy documentation

### CODE REVIEW

**Comment by chrisgaun** [comment]
@dkoshkin and @samba these are to address this COPS Request https://jira.mesosphere.com/browse/COPS-5355?filter=49400

**Comment by cmastr** [comment]
@SarahStegall @chrisgaun Where do we stand on this PR? Do we need reviews from Sam and Dimitri first?

**Comment by cmastr** [comment]
instances of add-on need to be changed back to addon for now.

**Comment by cmastr** [comment]
Resolving this PR with - https://github.com/mesosphere/dcos-docs-site/pull/2678

**Pull request closed without merging**
