### PR TITLE
Ck/port changes off kommander

### PR DESCRIPTION
**Pull request by ck4adventure**
## Jira Ticket
Before creating this pull request, please make sure you have a separate ticket for the docs team to track their work to review and merge, even for minor edits. If you need assistance, ask in the #doc-team channel on slack.

## Checklist
- [ ] Make sure you change all affected versions (e.g. 1.10, 1.11, 1.12, 1.13).
- [ ] Test all commands and procedures where applicable.
- [ ] Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects) if you are moving a page.

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing) for more information.

### CODE REVIEW

**Comment by ck4adventure** [comment]
taking commits from https://github.com/mesosphere/dcos-docs-site/pull/2764 to port directly into staging

**Comment by ck4adventure** [comment]
taking https://github.com/mesosphere/dcos-docs-site/pull/2757

**Comment by ck4adventure** [comment]
taking https://github.com/mesosphere/dcos-docs-site/pull/2761

**Comment by ck4adventure** [comment]
@russurquhart1 this is the PRs that were pointed at `kommander` all rolled into one. Passing this back over to you for normal docs publishing processes

**Comment by samvantran** [comment]
Can we also include this PR https://github.com/mesosphere/dcos-docs-site/pull/2745? Doesn't look like it made the cut into staging/is public in docs site

**Comment by samvantran** [comment]
@russurquhart1 please address my comments from the different PRs that Christina cherry picked into this one as not all were resolved/responded to.

**Comment by ck4adventure** [comment]
> Can we also include this PR #2745? Doesn't look like it made the cut into staging/is public in docs site

Adding it in now @samvantran

**Comment by gracedo** [comment]
@ck4adventure Can you include the commits in this PR as well? Looks like they are also missing from `staging` https://github.com/mesosphere/dcos-docs-site/pull/2743

**Pull request merged**
