### PR TITLE
[Archive] Kommander 1.2/1.3 + Konvoy 1.6/1.7

### PR DESCRIPTION
**Pull request by mwrightd2**
## Jira Ticket

https://jira.d2iq.com/browse/D2IQ-87705

## Description of changes being made

Archiving versions 1.2/1.3 of Kommander and 1.6/1.7 of Konvoy.

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-4408.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

### CODE REVIEW

**Comment by cmastr** [comment]
YESSSS!

**Review by vacas5 — APPROVED** [review]

**Comment by cneth** [comment]
Just a note that in addition to this PR, we also need to update these two pages:

https://docs.d2iq.com/dkp/kommander/1.4/archives/
https://docs.d2iq.com/dkp/konvoy/1.8/archives/

To indicate which versions are now archived.

**Review by cneth — APPROVED** [review]

**Comment by cmastr** [comment]
Following up this PR with a separate one to change the instructions.

**Comment by cmastr** [comment]
> Just a note that in addition to this PR, we also need to update these two pages:
> 
> https://docs.d2iq.com/dkp/kommander/1.4/archives/ https://docs.d2iq.com/dkp/konvoy/1.8/archives/
> 
> To indicate which versions are now archived.

Done in #4466

**Pull request merged**
