### PR TITLE
Update tutorials and configuration with 2.1.0 release versions in docs page

### PR DESCRIPTION
**Pull request by alembiewski**
Signed-off-by: Alex Lembiyeuski <alembiyeuski@d2iq.com>

## Jira Ticket

[Update tutorials with 2.1.0 release versions in docs page](https://jira.d2iq.com/browse/D2IQ-91193)

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-<add_pr_##_here>.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

### CODE REVIEW

**Comment by gvasquezvargas** [comment]
Hey @alembiewski! I think the MNIST SPARK tutorial is missing in this PR. In Confluence it still has the `rc.0` tag, but I guess that should be updated as well, right?
Otherwise, everything I have copied all these changes to Confluence already ✅

**Comment by alembiewski** [comment]
Good catch, @gvasquezvargas! We actually need to remove the MNIST Spark tutorial since we no longer include Horovod

**Comment by MessKon** [comment]
cannot see any more references to `rc0` or `dkp/kaptain` (for doc links) and the values and versions seem correct.
but as Gabi and you call out, there's many references to `horovod` in the `examples-stanging` directory and 1 in the tests directory.
I assume that the ones in the `examples-stanging` should be addressed as part of this PR?

**Review by gvasquezvargas — APPROVED** [review]
Copied all of this to Confluence as well ✅ I think it would be easier for me if we pull a new PR for all the Spark and Horovod stuff? That way I would not have to manually compare what I have copied to confluence already and what not.

**Review by MessKon — APPROVED** [review]
approving, assuming that references to horovod will be addressed in another PR ✅ 
(branch is out of date with latest main)

**Pull request merged**
