### PR TITLE
Documentation or jobs-with-dependencies

### PR DESCRIPTION
**Pull request by timcharper**
## Jira Ticket

D2IQ-71527

### CODE REVIEW

**Comment by pierrebeitz** [comment]
@timcharper i like the structure and iterated upon it.

**Comment by cmastr** [comment]
@timcharper as part of this PR, can we please update the Release Notes with a link to this new section? The description already exists, just needs a link: https://docs.d2iq.com/mesosphere/dcos/2.2/release-notes/2.2/#jobs-with-dependencies

**Review by cmastr — APPROVED** [review]

**Comment by timcharper** [comment]
@cmastr I've done as you've requested, does that look OK?

**Review by cmastr — APPROVED** [review]

**Comment by cmastr** [comment]
perfect! thank you sir.

**Pull request merged**
