### PR TITLE
[Konvoy] Implement Kube 1.23 bump to docs site

### PR DESCRIPTION
**Pull request by mwrightd2**
## Jira Ticket

https://jira.d2iq.com/browse/D2IQ-90609

## Description of changes being made

Bumped kuber versions for 2.2/2.3

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-4556.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

### CODE REVIEW

**Review by cneth — APPROVED** [review]
Approved, as long as we remove the 2.2 pages as we're not bumping Kubernetes in 2.2...

**Review by mmcelroy91 — APPROVED** [review]

**Comment by DreadPirateShawn** [comment]
Note, @mwrightd2 confirmed via Sack (currently on PTO) that the 2.2 docs changes were an overzealous find-and-replace, and he plans to remove the 2.2 changes and repost.

**Comment by DreadPirateShawn** [comment]
(Feel free to remove the "DO NOT MERGE" label once the PR has been updated without 2.2 changes.)

**Comment by cmastr** [comment]
@mackdubya can you remove the 2.2 stuff so we can merge this?

**Pull request merged**
