### PR TITLE
redirect for dispatch broken link

### PR DESCRIPTION
**Pull request by cmastr**
## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Create new PRs against `develop`, or `main` for hotfixes to production.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

### CODE REVIEW

**Comment by msdolbey** [comment]
Making a quick change - standby, @cmastr

**Review by fatz — DISMISSED** [review]
I'm pretty sure these rules get applied in order so I would suggest moving this new rule before line 45 https://github.com/mesosphere/dcos-docs-site/blob/64178ebfcc7726027142f57b475c32427148ab67/s3config.json#L45

**Comment by msdolbey** [comment]
Oh, that's a good point - @fatz - 

Actually, because of that - this may be unnecessary - /ksphere/dispatch should already re-direct to /dkp/dispatch.

Standby.

**Comment by msdolbey** [comment]
We're good already here - so it will be weird locally no matter what, and seemingly on dev, but that is the same for dispatch as it is for konvoy/kommander, etc.

But, for the real show, it's good on the docs site as is already.

FYI @cmastr - I think we can close this.
https://user-images.githubusercontent.com/5703649/146585855-e14348c7-3acb-4062-b79d-824d1a96c013.mov

**Comment by cmastr** [comment]
oh weird. Why is it not working for @gflorinskaya then??

**Comment by cneth** [comment]
Hey @msdolbey - not sure why you say these are working...   I just tried it this link:

https://docs.d2iq.com/ksphere/dispatch/latest/

And it returns a not found.  However, we can see what the problem is too, it's redirecting to here:

http://docs.d2iq.com/dkp/dispatch/1.2/

@cmastr The problem is this rule:

{ "Condition": { "KeyPrefixEquals": "dkp/dispatch/latest/" }, "Redirect": { "HostName": "$REDIR_HOSTNAME", "ReplaceKeyPrefixWith": "dkp/dispatch/1.2/", "HttpRedirectCode": "307" } },

We archived 1.2 so this is why you get the dead links.   This should be 1.4 here.     I think if you make just this change and not the one you added, it will work.

**Comment by msdolbey** [comment]
Oh - I see @gflorinskaya comment - it's because dispatch's 'latest' was never updated - lemme push something.

**Comment by msdolbey** [comment]
@cmastr - ready to roll
@cneth - check too if you have some time.

**Review by cneth — APPROVED** [review]
This is the right fix.   Here's the current sequence of redirects:

$ curl -L -v https://docs.d2iq.com/ksphere/dispatch/latest/  2>&1 >/dev/null | grep -e GET -e location:
> GET /ksphere/dispatch/latest/ HTTP/2
< location: http://docs.d2iq.com/dkp/dispatch/latest/
> GET /dkp/dispatch/latest/ HTTP/1.1
> GET /dkp/dispatch/latest/ HTTP/2
< location: http://docs.d2iq.com/dkp/dispatch/1.2/
> GET /dkp/dispatch/1.2/ HTTP/1.1
> GET /dkp/dispatch/1.2/ HTTP/2

The ksphere -> dkp happens on the first redirect, then the 'latest' -> '2.1' on the second round, which is what fails.   So this will solve it.

**Comment by msdolbey** [comment]
> This is the right fix. Here's the current sequence of redirects:
> 
> $ curl -L -v https://docs.d2iq.com/ksphere/dispatch/latest/ 2>&1 >/dev/null | grep -e GET -e location:
> 
> > GET /ksphere/dispatch/latest/ HTTP/2
> > < location: http://docs.d2iq.com/dkp/dispatch/latest/
> > GET /dkp/dispatch/latest/ HTTP/1.1
> > GET /dkp/dispatch/latest/ HTTP/2
> > < location: http://docs.d2iq.com/dkp/dispatch/1.2/
> > GET /dkp/dispatch/1.2/ HTTP/1.1
> > GET /dkp/dispatch/1.2/ HTTP/2
> 
> The ksphere -> dkp happens on the first redirect, then the 'latest' -> '2.1' on the second round, which is what fails. So this will solve it.

Wow - you went deeper than I ever did on this. Thanks for showing the work on my proof set, @cneth

**Review by gflorinskaya — APPROVED** [review]
Looks good to me, https://docs.d2iq.com/dkp/dispatch/1.4/ should work

**Pull request merged**
