### PR TITLE
Review Minio 0.1.0 service docs

### PR DESCRIPTION
**Pull request by SarahStegall**
## Description
https://jira.mesosphere.com/browse/DCOS-45551
## Urgency
- [ ] Blocker 
- [x] High
- [ ] Medium

Original files from PR1168 were pulled to local branch, edited. Since I can't push them back to that non-Mesosphere repo, I'm creating this PR so that they can be reviewed, edited, approved and eventually merged.

These documents are seriously in need of work. I have made as many changes as I could, and the parts where changes need to be made by the author have been noted as in-line comments in the Markdown files.
Changes include:

- Renaming several files to conform with Mesosphere directory name style
- Moving the Recover section from Troubleshooting to Operations

Additional material is needed for:

- Disk Caching page needs an example of a config file using required settings

- Why is the Edge-LB Pool Config info in the Quick Start Guide? See note in files.
- Mount Volumes procedure does not include text commands. Screenshots are not a substitute for text.

Other issues are called out as comments in the relevant files.

### CODE REVIEW

**Comment by ryadav88** [comment]
@SarahStegall for please add any comments as PR comments so we can assign to the developer to resolve. In any case, I've ask the developer to go through each file and look through any commented section.

**Comment by Mohini6649** [comment]
@SarahStegall Please provide me with the write access on this PR to make the required changes.

**Comment by Mohini6649** [comment]
@SarahStegall I am not able to commit the required changes on github as not having the required permission.Request you to provide me the access for the same.

**Comment by SarahStegall** [comment]
Developer needs to set up a remote that points to our account:
```git remote add mesosphere https://github.com/mesosphere/dcos-docs-site.git```
Then they need to fetch from that remote:
```git fetch mesosphere```
Then reset their branch to where ours is:
```git checkout -b DCOS-45551
git reset --hard mesosphere/DCOS-45551```
Then they will be up to date with where we are. When they are ready, they can make a PR from their repo’s `DCOS-45551` to ours

**Comment by ryadav88** [comment]
@SarahStegall https://github.com/mesosphere/dcos-docs-site/pull/1877 addresses your comments. it will merge the changes to this PR.

**Comment by SarahStegall** [comment]
This PR has been superseded by PR 1877 and PR1897.

**Pull request closed without merging**
