### PR TITLE
removing hiding of 2.2 for GA

### PR DESCRIPTION
**Pull request by cmastr**
Signed-off-by: Casie Oxford <coxford@d2iq.com>

## Jira Ticket

No JIRA for this. 

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-4266.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

### CODE REVIEW

**Review by vacas5 — APPROVED** [review]
I'm ready if you're ready

**Comment by cmastr** [comment]
> I'm ready if you're ready

This should wait till we get the official thumbs up for GA. Added do not merge.

**Comment by cmastr** [comment]
Dolbs added one that we forgot.

**Review by msdolbey — APPROVED** [review]
👍 
good

**Pull request merged**
