### PR TITLE
new landingpage

### PR DESCRIPTION
**Pull request by pierrebeitz**
This changes the landingpage to match [this sketch](https://mesosphere.invisionapp.com/d/main#/console/19986194/418690946/inspect). 

have a look at one of the latest comments for a screencast or screenshot.

### CODE REVIEW

**Comment by danielone** [comment]
@cmastr is best to provide text for all these as she is the docs boss =)

**Comment by danielone** [comment]
@cmastr should "Frequently-asked questions (FAQ)" be "Frequently Asked Questions (FAQ)" ?

**Comment by danielone** [comment]
@pierrebeitz i would use existing margins on site for ease of implementation. 
Access to project on Invision granted. 
Work with Nan Wang nwang@d2iq.com on design reviews of this please

**Comment by cmastr** [comment]
Kommander - Deliver federated management and governance across disparate clusters for any on-premise or cloud Kubernetes distribution.
Konvoy - A packaged set of integrated operational services for Kubernetes so you can get up and running quickly and easily.
Dispatch - Rapidly build, test, and manage an application's lifecycle using industry best practices and modern GitOps processes.
DC/OS - A wide range of enterprise-grade capabilities for strong Day 2 operations of cloud native services.

**Comment by pierrebeitz** [comment]
* updated the PR with the new images (already included those for kubeflow and conductor as well to save work in near future) and the texts given in the comment by @cmastr ☝️. See the updated description for a screenshot of the current state.

* i piped the pngs through optipng, which shaved off between 40% and 60% of file size with no quality loss.

i'd consider this mergeable now as it looks like a sensible step on our way to fully resembling [the sketch](https://mesosphere.invisionapp.com/d/main#/console/19986194/418690946/inspect).

**Comment by danielone** [comment]
Hi Pierre, I thought going to use SVG ? Good reason not too?

Kaleb, what format best for such type of images for the .com properties?

**Comment by pierrebeitz** [comment]
Hi @danielone! Svg would be great. Got svgs from Nan though. Will use SVG if someone provides those.

**Comment by danielone** [comment]
Sure I believed I mentioned on previous reply to just contact Nan directly to get those. I will mention to her on Monday to send to you 

Best,
Daniel

**Comment by danielone** [comment]
@pierrebeitz 
Looking really good!
- please use existing current font and spacing cadence of site so if body text is 16px on existing site then please use that. Same with existing headers etc... We are learning too what styles docs was using so likely good there is some docs on docs existing styling perhaps generated from this so design and FEs can be 1to1.
- mockup size should of been for 1440px (high rez target screen size) and not 1024px so issue on our end and will check InVision too. 
- please change casing of FAQ to "Frequently-Asked Questions (FAQ)"

**Comment by pierrebeitz** [comment]
Thanks for the feedback @danielone!

Already using existing fonts and latest descriptions, don't we? 

Will reorder the items. 

Casing is autogenerated from pages titles. I think that's better done in a separate PR that checks all of those.

**Comment by danielone** [comment]
Pierre, check out Cassie’s Comment with latest descriptions in the PR. I didn’t see those there.  

Best,
Daniel

**Comment by pierrebeitz** [comment]
there must be a misunderstanding. i made an image to depict the comment with the descriptions matching the current state. 

img

if something is wrong here, i'd love to have really specific feedback about which texts you mean. thank you!

please note that i will change the order of entries according to your feedback above.

**Comment by danielone** [comment]
Ahh yes you are correct Pierre. Excuse me. 
Thanks for the visual.

**Comment by cmastr** [comment]
This all looks great to me! Are there things we're still needing for this?

**Comment by danielone** [comment]
Yes filter stuff 
Booked you to talk about

**Comment by pierrebeitz** [comment]
*From a technical perspective* we could ship without filters. That enables adding more items to the landingpage.

**Comment by danielone** [comment]
@pierrebeitz to confirm, you have reordered the items just not in the screenshot right?

**Comment by danielone** [comment]
@pierrebeitz 

I sync'd with @cmastr this AM.

- we need to move fwd with the filters before release of this this way DC/OS not treated as 2nd class citizen (as will be much lower down in new design) so please get started there (if want other PR for up to you of course)
- The animated bouncy balls background like on d2iq.com are key touch. @cujojp  did these.
- on hover of filter button, behavior should be similar or same as on d2iq.com. Ideally animate icons too. @cujojp  did these
- on click of a filter button, the non-selected ones should be slightly darkened or muted a bit and the active one should remain the same. Partner with Nan on design of that. 
- to reset to "all" view, for now just clicking on the active filter will reset to the "all view" and all buttons will be returned to default state If you and Nan have a proposal for an additional explicit filter, I am very open to your ideas there. Could be as simple a View All bold link below the filters (above the horizontal line). This is optional.

**Comment by joinan06** [comment]
test

**Comment by joinan06** [comment]
I am working on the non-selected button design and reset button 'View All'. And I will update to Invision later today. @pierrebeitz Let me know if you find anything needs to be adjusted.

**Comment by cmastr** [comment]
**KUDO**: A declarative approach for building full-lifecycle Kubernetes operators.

**Comment by danielone** [comment]
> **KUDO**: A declarative approach for building full-lifecycle Kubernetes operators.

@cmastr I think we will need something longer to better match with the other descriptions. Recommend longer or perhaps another sentence about how they tie in with rest of ksphere/d2iq products. Can tap @gerred for inspiration.

**Comment by danielone** [comment]
@cmastr will supply and sublinks for Kudo (like FAQ shortcut for Konvoy)

@pierrebeitz  for Kudo, please show an external link icon next to the title (right of it) and also a badge "CNCF Silver Member" to the right of that. For the color of the badge, perhaps just an outline style like from UI-Kit but perhaps a bit more padding. Trust your eye on spacing, just take a pass there please.

**Comment by pierrebeitz** [comment]
Hi @cmastr and @danielone.

I have some progress to share here.

Please note upfront that:

* i did not address your remarks regarding KUDO yet.
* i just copied the bubble-animation
* i just copied most parts of the filter buttons (and rearrange their inner components - like the animated steering wheel and so on - a bit)
* i made up an disabled-state for the filter-buttons (50% opacity)
* the datasphere button is already present in the code and just waits to be shown
* we can remove the latest commit to restore the (IMHO mergeable) state we had before
* the bubbles don't work out of the box as i had hoped. there's some manual work to do if we want them to be like in the sketch. i don't have very much time to work on the docs, so i hope you like one of the following states as a first step.

## the current state of this PR

current bubbles

## an easy to implement alternative

bigger bubbles

----------------------

again i think that the current state would be mergeable. let me know what you think.

**Comment by joinan06** [comment]
@pierrebeitz Good job, thank you! 

I want to add two points here:
- In the filter, please use a 30% of the black (#000000) overlay on non-selected buttons. 
- Please add a 'View All' text button below the filters to reset to the "all" view. 
You can find the reference on Invision:
https://mesosphere.invisionapp.com/share/QEXM102M7PG  (Password:docs@2020!)

**Comment by danielone** [comment]
@pierrebeitz  great stuff
@joinan06  and I looked at the following together and and here is additional issues on top of what she raised
- The bubbles are ONLY supposed to appear in the region of the filters, NOT across the entire page. It is too much for the entire page. 
- the sub links for each product are now missing (e.g., Release Notes)
- When filter pressed, it can be depressed to reset to all or click on View All as @joinan06 indicated above
- Kudo and datasphere stuff can wait and can be in a diff ticket and PR as you best see fit and @cmastr and doesn't need to delay merge from our end. @joinan06 mocking Datasphere w/Kudo up

**Comment by pierrebeitz** [comment]
@danielone thanks for the feedback

1. **so the state of the first image is almost acceptable?** please note that if i make the "bubble-container" even smaller, the bubbles will become smaller and won't travel to the sides. adjusting this would need some time of tweaking - and i don't have much time for the docs. maybe the original creator can help here?
2. oh well. sorry for the confusion. i created those images in a "tweaked" environment for fast feedback. the links are present in the current state of this PR.
3. yes, that's how it is currently implemented.
4. 👍 

------------------

here's a video to illustrate points 1 and 2:

screencast 2020-06-13 10-53-51

**Comment by pierrebeitz** [comment]
addressed all feedback. here's a screencast:

docs

i edited the bubbles-svg by hand to make it look better than in the screenshots above.

**Comment by pierrebeitz** [comment]
i improved on the bubbles-animation in that users now can experience it without loading 180kb for the TweenMax animation library. Maybe Kaleb wants to reuse that on the main page - pinged him on slack.

**Comment by cmastr** [comment]
> > **KUDO**: A declarative approach for building full-lifecycle Kubernetes operators.
> 
> @cmastr I think we will need something longer to better match with the other descriptions. Recommend longer or perhaps another sentence about how they tie in with rest of ksphere/d2iq products. Can tap @gerred for inspiration.

How's this one?

KUDO is a Universal Operator that orchestrates workload-specific procedures using a declarative spec, saving you time from writing thousands of lines of code so you can get to market faster.

**Comment by cmastr** [comment]
KUDO links:

Release Notes - https://kudo.dev/docs/runbooks/kafka/release-notes.html
What is KUDO - https://kudo.dev/docs/what-is-kudo.html
Getting Started - https://kudo.dev/docs/developing-operators/getting-started.html

**Comment by danielone** [comment]
@cmastr nice so all kudo needs is a new scene graphic from anne marie as per your sched to request

@pierrebeitz  what do you mean by "i edited the bubbles-svg by hand to make it look better than in the screenshots above." ? great stuff in general !

**Comment by danielone** [comment]
@cmastr i think we are good to go on this unless only want to publish with kudo which i would recommend as so close and only need graphic and so 1to1 with spheres on d2iq.com
Description length looks good to me. Gerred probably your best feedback point there =)

**Comment by joinan06** [comment]
> Kudo and datasphere stuff can wait and can be in a diff ticket and PR as you best see fit and @cmastr and doesn't need to delay merge from our end. @joinan06 mocking Datasphere w/Kudo up

@cmastr @danielone I have added KUDO to Datasphere in our Invision mockups.  Please take a look. 

Invision: https://mesosphere.invisionapp.com/share/QEXM102M7PG 
Password: docs@2020!

**Comment by cmastr** [comment]
Looking really great! I think we still need to add Kubeflow to ksphere and add the Datasphere category. Then, when we get docs from Conductor, we can add that to ksphere as well.

**Comment by danielone** [comment]
@casie - great but do want to wait to release until have all that or something else?

Best,
Daniel

**Comment by joinan06** [comment]
Hi, @cmastr I still need the KUDO icon for Datasphere category. I'm using a placeholder now. Can you ask Anne-Maria for help?  Thank you!

**Comment by cmastr** [comment]
> @Casie - great but do want to wait to release until have all that or something else? Best, Daniel
> […](#)
> On Jun 17, 2020, at 7:16 AM, Casie Oxford ***@***.***> wrote: ﻿ Looking really great! I think we still need to add Kubeflow to ksphere and add the Datasphere category. Then, when we get docs from Conductor, we can add that to ksphere as well. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

I want to hold this until we have Conductor, Kubeflow and KUDO. Goal is to merge this in tandem with the Conductor release, end of June.

**Comment by cmastr** [comment]
> Hi, @cmastr I still need the KUDO icon to complete the Datasphere page. I'm using a placeholder now. Can you ask Anne-Marie for help? Thank you!

Ok, will ask her now!

**Comment by pierrebeitz** [comment]
integrated products as per our plan:

localhost_3000_

note: 
- KUDO-links are opened in a new tab. because it felt weird to me otherwise.
- conductor-links will be generated once we got conductor-content

@cmastr i can not find the conductor info text on the interwebs and would love if you could send it along my way (again?) 😬

**Comment by cmastr** [comment]
> integrated products as per our plan:
> 
> localhost_3000_
> 
> note:
> 
> * KUDO-links are opened in a new tab. because it felt weird to me otherwise.
> * conductor-links will be generated once we got conductor-content
> 
> @cmastr i can not find the conductor info text on the interwebs and would love if you could send it along my way (again?) 😬

Yes, will see what I can get from product marketing since Conductor hasn't gone out yet, not sure if they have anything for us to steal. Will get you something!

**Comment by cmastr** [comment]
**Conductor**: Conductor is a an interactive learning platform designed to accelerate onboarding to cloud-native technologies. @pierrebeitz

**Comment by danielone** [comment]
Pierre
Please see the mock-up for kudo where to include an external link icon 
Yes all kudo should open in new tab. That was expected on our end too. 

Best,
Daniel

**Comment by pierrebeitz** [comment]
@danielone do we want that external link indicator on all external links?

asking the mock-up seems to suggests that only the headline gets an indicator. if that's correct: what's the rule for that?

docs-1 2-4 2020-06-26 16-28-39

apart from that: let's please solve that in a separate PR if it's not a special rule for the KUDO-link on the frontpage.

**Comment by danielone** [comment]
We didn’t want to overwhelm the row with too many external icons so we thought to just keep it at the top level and perhaps can be clear for the sub items; keep light for now. So kind of special rule here because typically External links should have the external icon but when they’re in groups like this I can get a little bit overwhelming. We’ve taken same approach in kommander. 

Best,
Daniel

**Comment by pierrebeitz** [comment]
@danielone thanks. we'll make a special rule here.

we do have an UX-issue due to the order of the items. the ksphere-button looks like it is broken (as it removes only items that are down below the screen):

screencast 2020-06-26 16-43-31

**Comment by danielone** [comment]
Do external links *always* show external icons **programmatically ?!** If so, don’t waste time on special coding pls.  If manual, then please proceed. 

Best,
Daniel

**Comment by joinan06** [comment]
Hi @pierrebeitz, we have a small change here.
We need to change the product title 'Kubeflow' to 'KUDO for Kubeflow'. I have updated the Invision mockups, please take a look.
https://share.getcloudapp.com/jkuQmd6o
https://mesosphere.invisionapp.com/share/QEXM102M7PG  password:docs@2020!

**Comment by pierrebeitz** [comment]
closing this as all change is contained in #3061

**Pull request closed without merging**
