### PR TITLE
D2IQ-71605 - [dcos] add new job-table fields to GUI docs

### PR DESCRIPTION
**Pull request by pierrebeitz**
closes D2IQ-71605

## Jira Ticket

https://jira.d2iq.com/browse/D2IQ-71605

## Description of changes being made

we added a couple new fields to the jobs table and now incorporate those in the docs.

## Checklist
- [x] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [x] Test all commands and procedures, if applicable.
- [x] Create your PR against `staging`, not `master`. 
- [x] Update all links if you are moving a page.
- [?] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> ie `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://wiki.d2iq.com/display/ENG/Contributing+to+Docs) for more information.

## screenshot

Jobs - D2iQ Docs 2020-09-22 13-50-11

### CODE REVIEW

**Comment by cmastr** [comment]
@pierrebeitz if this is new for 2.2, can we add a short description in the release notes, with a link to these topics? Check out what Greg did for CSI Driver stuff for inspiration.

**Review by cmastr — APPROVED** [review]

**Comment by pierrebeitz** [comment]
@cmastr we have kind of a special situation here, as this is added for

* DC/OS 1.13.10
* DC/OS 2.0.7 
* DC/OS 2.1.2
* DC/OS 2.2.0

not sure how to handle this best.

**Comment by cmastr** [comment]
> @cmastr we have kind of a special situation here, as this is added for
> 
> * DC/OS 1.13.10
> * DC/OS 2.0.7
> * DC/OS 2.1.2
> * DC/OS 2.2.0
> 
> Also anyone can update their UI on even older clusters to get this feature.
> 
> Not sure how to handle this best.

Wow, that's really messy in docs. Correct way would be to update release notes for all of those versions above and then add a note to the page that the descriptions are on that indicates the patch number needed to see the feature. 

For example- **Note**: The CPU, Memory, Disk, and GPU fields only display when you have applied DC/OS patch 2.1.2 or higher. 

I'd be ok just calling this feature out in 2.2, but not in other versions. But probably need @vinodkone to make a call here.

**Comment by vinodkone** [comment]
Can't we add a `*` next to the new field names and mention at the bottom of the page these are available from  DCOS UI version X? It's tied to the DCOS UI component version than DCOS version FWICT. Also, I dont see changes to 1.13 doc pages though it's mentioned in the description?

**Comment by pierrebeitz** [comment]
> Can't we add a * next to the new field names

simple enough. i like that. WDYT @cmastr?

> I don't see changes to 1.13 

that's because [those docs are not as extensive](https://docs.d2iq.com/mesosphere/dcos/1.13/gui/jobs/) and i did not want to invest the time to discuss whether it's worth backporting the docs from 2.0/2.1 as 1.13 will soon be outdated. do you agree with this decision or shall we "backport"?

**Comment by vinodkone** [comment]
No need for 1.13

Thanks,
Vinod

**Comment by cmastr** [comment]
To do this right, it needs to be in the release notes for all versions, linked from the rn to the topic, then needs to be more prominently displayed than on the bottom of the page. You can do an asterisk by the field name and a description right under the table. For 2.2 and going forward, no need for asterisk since it went into the 2.2 version.

**Comment by pierrebeitz** [comment]
quick voting please:

# 1 With an InfoBox (🚀 )

Jobs - D2iQ Docs 2020-09-24 16-35-24

# 2 Unstyled (❤️)

Jobs - D2iQ Docs 2020-09-24 16-38-02

# 3 Smaller and aligned to the right (🎉 )

Jobs - D2iQ Docs 2020-09-24 16-50-25

------------------

i did not implement the suggested change regarding the release notes just yet, as the files don't exist yet and i don't know who is to put those together.

it would be awesome to have them in place already. thinking about that `draft`-flag again, @cmastr - how about marking subtrees that should not be rendered when their metadata says `draft: true`? that would account for a single page, like "release notes" and a new version of a product, like `dc/os 2.3` as well as get rid of this `DO_NOT_BUILD`-stuff.

**Comment by vinodkone** [comment]
I vote option 1.

Regarding release notes, just add them to CHANGES.md file for now and @cmastr  can pull it into release notes when it's time to release it.

**Comment by pierrebeitz** [comment]
👍 that's the version i pushed. so i guess this PR could now be merged.

**Comment by cmastr** [comment]
Yep I agree with Vinod. Merging.

**Pull request merged**
