### PR TITLE
(kommander 2.2) Fix kommander CA secret name in kubetunnel docs

### PR DESCRIPTION
**Pull request by branden**
## Jira Ticket

https://jira.d2iq.com/browse/COPS-7159

## Description of changes being made

This updates the location of the kommander CA secret. This was changed in Kommander 2.1.

## Checklist

- [x] Test all commands and procedures, if applicable.
- [x] Create new PRs against `develop`, or `main` for hotfixes to production.
- [x] Update all links if you are moving a page.
- [x] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

### CODE REVIEW

**Review by gracedo — COMMENTED** [review]
I think changes into 2.1 need to go into `main`, and at some point there is a merge of `main` into `develop` (not sure if this is automated yet but we're not supposed make the same changes in develop and wait instead for that merge). 2.2 changes go into `develop` so that change is fine here. Is that the right process @vacas5 @msdolbey ?

**Comment by vacas5** [comment]
yep exactly. Since we want this stuff in both prod and dev, we'll need separate PRs, one against main for the 2.1 docs, and one against develop for the 2.2 docs. I routinely merge main back into develop

**Review by vacas5 — CHANGES_REQUESTED** [review]
see my comment about splitting into two PRs

**Comment by msdolbey** [comment]
I'll make a quick change for that.

**Comment by msdolbey** [comment]
NM - you got it @branden !

**Review by msdolbey — APPROVED** [review]
👍 
Good tunnel work

**Review by vacas5 — APPROVED** [review]

**Pull request merged**
