### PR TITLE
add broken Homebrew link

### PR DESCRIPTION
**Pull request by mmcelroy91**
## Jira Ticket
No ticket

## Description of changes being made
broken Homebrew link fixed

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-4439.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

### CODE REVIEW

**Review by JohnB64-JBV — APPROVED** [review]
Fixed! Thank you!

**Review by msdolbey — COMMENTED** [review]
I also didn't realize this until now, but this Install topic is in caps (pages/dkp/konvoy/2.2/Install/index.md) - rather than lower case.
We should probably change this for future us. 
Is this linked anywhere else yet? We might just want to move this file right now, too.

**Comment by mmcelroy91** [comment]
Matt, do you mean I in Install shouldn't be capitalized?

**Comment by msdolbey** [comment]
Yeah - generally the URLs shouldn't be. This one is already published, so I don't know if it makes too much of a difference now.

**Comment by mmcelroy91** [comment]
Ah, so I did that when I created the page in VSCode since it was a new page, right?  My bad!  Old English habit of capitalization.

**Comment by mmcelroy91** [comment]
Maybe I fix it in Confluence since it's already been migrated over there?

**Comment by mwrightd2** [comment]
@msdolbey I'll rename the path with the proper capitalization, also fixed other links and looks good from my end @mmcelroy91. Approving and merging.

**Review by mwrightd2 — APPROVED** [review]

**Comment by mmcelroy91** [comment]
Thanks Mack, obviously the other link was wrong too... this was literally the first thing I did in VSCode, so it is fully messed up!  HA!  Thanks for your help you guys.

**Pull request merged**
