### PR TITLE
Qa/install delete quick start edits

### PR DESCRIPTION
**Pull request by msdolbey**
## Jira Ticket
Just re-committing the stuff from these two:
https://github.com/mesosphere/dcos-docs-site/pull/2881
https://github.com/mesosphere/dcos-docs-site/pull/2878

## Description of changes being made
You can review from here: 
https://github.com/mesosphere/dcos-docs-site/pull/2881
https://github.com/mesosphere/dcos-docs-site/pull/2878

## Checklist
- [ ] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [ ] Test all commands and procedures, if applicable.
- [ ] Create your PR against `staging`, not `master`. 
- [ ] Provide an estimated date for deploying the doc change. Note: Improvements or fixes can be merged ASAP. 
- [ ] Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects) if you are moving a page.

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing) for more information.

### CODE REVIEW

**Comment by msdolbey** [comment]
@cmastr's comments on install page.
See slack thread, but here's my response:

Ok, coming in a bit late on this. We should not only have a quick start from a customer perspective. They are not going to be looking for "quick start" when they google "Konvoy Install" or whatever. SO I understand the intention here. But if we're gonna delete the Install topic, we then need to rename the Quickstart to "install".
Plus, I hate the term Quickstart in general. Quick for whom exactly? Is quick 1 minute or 1 hour? Let's just not use this. @russ Urquhart

Casie Oxford < 1 minute ago
So will need to get some updates to this PR before I'm comfortable merging this one.

**Comment by msdolbey** [comment]
@cmastr 
Point taken, I'm still going to delete the install page as it is, and rename the quick start to install.

But for reference, a `quickstart`, including the build time, is probably around 30 minutes? But, depends on how much one messes around with the settings and their cloud providers, etc.

**Comment by msdolbey** [comment]
@cmastr -
looks good after building locally to me after renaming

**Comment by cmastr** [comment]
ok, yes @msdolbey that works renaming the page. I'm going to run a local build first since there are 60 some odd pages changed.

**Comment by cmastr** [comment]
@juliangieseke we'll promote Matt's PR instead of PR #2885

**Pull request merged**
