### PR TITLE
Add Limits page to DC/OS Spark 2.3.0-2.2.1-2 docs

### PR DESCRIPTION
**Pull request by samvantran**
## Description
Addresses: [SPARK-691](https://jira.mesosphere.com/browse/SPARK-691)
This PR updates DC/OS Spark docs to report how much scale-testing we've done.

DC/OS Spark has been run on a 2.5K core cluster. 
The plan was to test on 10K cores but that was cost prohibitive.

## Urgency
- [x] Medium

### CODE REVIEW

**Comment by imaxxs** [comment]
I am not sure if we should put all our Spark CPU test results in limitations as it seems to be right now. 

Again, @keithchambers please advice.

**Comment by susanxhuynh** [comment]
@samvantran I think we need the changes in the spark-build repo. We would update this repo if we wanted to backport to previous Spark releases.

**Comment by susanxhuynh** [comment]
@samvantran Yes, this is the repo for that version, 2.3.0-2.2.1-2. In order to make sure the doc is updated for future releases, the spark-build repo has to get updated (we copy the docs from `spark-build` into the dcos-docs-site repo for each new release).

**Comment by samvantran** [comment]
@susanxhuynh gotcha - created a new PR on spark-build: https://github.com/mesosphere/spark-build/pull/286 
I guess that means we can close this PR and since you're creating a new Spark release this will be captured (if we merge PR 286 first)?

**Comment by keithchambers** [comment]
LGTM!

**Comment by samvantran** [comment]
Closing this PR since https://github.com/mesosphere/spark-build/pull/286 was merged. Susan plans to build a new spark release soon and the docs there will be copied here when she does that.

**Pull request closed without merging**
