### PR TITLE
Add changelog for 0.3.0 couchbase package release

### PR DESCRIPTION
**Pull request by Gupta-Amrit**
## Description
Add changelog for 0.3.0 couchbase package release.

DO NOT MERGE until the following PR is merged:
https://github.com/mesosphere/universe/pull/2220

## Urgency
- [ ] Blocker 
- [ ] High
- [ ] Medium

### CODE REVIEW

**Comment by ryadav88** [comment]
Internal Jira: https://jira.mesosphere.com/browse/DCOS-50473

**Comment by SarahStegall** [comment]
Added DO NOT MERGE label per Ravi's direction in Description.

**Comment by SarahStegall** [comment]
Label removed per Ravi.

**Comment by ryadav88** [comment]
Universe PR merged: https://github.com/mesosphere/universe/pull/2220. @SarahStegall please merge this as well.

**Pull request merged**
