### PR TITLE
[DCOS-61614] Add release docs for Cassandra 2.8.0-3.11.5

### PR DESCRIPTION
**Pull request by farhan5900**
## Jira Ticket
[DCOS-61614](https://jira.mesosphere.com/browse/DCOS-61614)

## Description of changes being made
* Adds updated docs for the release of Cassandra 2.8.0-3.11.5. Previous version 2.7.0-3.11.4 docs have been renamed to 2.8.0-3.11.5

## Checklist
- [x] Make sure you change all affected versions (e.g. 1.10, 1.11, 1.12, 1.13).
- [x] Test all commands and procedures where applicable.
- [x] Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects) if you are moving a page.

### CODE REVIEW

**Comment by cmastr** [comment]
Christina is no longer on the docs team, so removing her from review.

**Comment by viivek46** [comment]
@farhan5900 first of all this version should be 2.7.1-3.11.5, as we are upgrading SDK from 0.57.0 to 0.57.2 !

**Comment by cmastr** [comment]
@farhan5900 is this ready to merge now?

**Comment by farhan5900** [comment]
@cmastr Yes we can merge now.

**Pull request merged**
