### PR TITLE
Update requirements for Kaptain 

### PR DESCRIPTION
**Pull request by dmennell**
Please review the requirements section and verify the requirements: https://docs.d2iq.com/dkp/kaptain/2.0.0/install/dkp/#requirements

We appear to be "crossing streams" between "per host" requirements (RAM) and aggregate requirements (CPU).  Also, the math for 3 hosts and 25 vCPU does not come out evenly, so that would be a place for confusion

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-<add_pr_##_here>.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

### CODE REVIEW

**Comment by alembiewski** [comment]
@dmennell, thanks for your comments! I updated the requirement based on your suggestions. Please take a look

**Comment by msdolbey** [comment]
Had to fix up some yaml, but this looks good to me.

**Review by msdolbey — APPROVED** [review]
👍 
Geordi to the core

**Comment by dmennell** [comment]
Have we tried these requirements with the default deployments of Kommander (DKP Essentials)?  This is well below what used to be our bare minimum for even a default Kommander cluster.  Also, From Field experience, the root volume of the nodes needs to be larger to accommodate all the Images that are to be pulled.  I would Like Tommy Scherer and Bruce Jacobs from the Presales team to review.  I liked the idea of using aggregate CPU & Memory Minumums as it allows the user to slice and dice the CPU and Memory requirements as desired (larger nodes = fewer Daemon Set Pods) for their workloads.

**Comment by alexeygorobets** [comment]
hi @dmennell ,
from what I understand those requirements stated for freely available resources after all infrastructure (Kommander, Konvoy etc.) already installed:
```
...
verify that your cluster has the following resources freely available
...
```
Should we make it more explicit?
Or am I missing something?

We've reduced images sizes so it should be  44.2 GB = 31.8 GB  (base components) + 12.4 GB (CPU images) so I expect it to fit on the root volume of this size since Kaptain 2.0.0

**Review by andresmascl — APPROVED** [review]
No structural changes.  LGTM

**Review by gflorinskaya — APPROVED** [review]

**Comment by dmennell** [comment]
I may be an off base... But I would has anyone gotten a DKP Essentials cluster up with these specs?

    - 3 worker nodes
    - 8 CPU cores
     - 16 GiB of RAM
     - 60 GiB of Storage

all base commander functionality (monitoring, logging, backup, etc) plus Istio & kNative.  Then lay Kaptain down on top of that?  If that is just the base items, and no workload deployed, then we need to really call it out.  @bruced2iq thoughts?

**Comment by andresmascl** [comment]
> I may be an off base... But I would has anyone gotten a DKP Essentials cluster up with these specs?
> 
>     - 3 worker nodes
>     - 8 CPU cores
>      - 16 GiB of RAM
>      - 60 GiB of Storage
> 
> all base commander functionality (monitoring, logging, backup, etc) plus Istio & kNative.  Then lay Kaptain down on top of that?  If that is just the base items, and no workload deployed, then we need to really call it out.  @bruced2iq thoughts?
> 
> 

Hi @dmennell. I may be wrong here but As far as I understand no amount of resources is enough for deploying Kaptain if the resources in question are being used by other applications.   For this reason in order to deploy Kaptain I think resources not only need to be present in the cluster, but they need to also be available for allocation.  With these resources (3 worker nodes, 8 CPUs per node, 16 GiB in RAM per node, and 60 GiB of storage capacity per node) being freely available in in a fully deployed DKP 2.2.0 cluster, yes a deployment of Kaptain 2.2.0 was made successfully 😊

Please let me know if I can assist in any further testing.

**Comment by andresmascl** [comment]
>

**Comment by andresmascl** [comment]
> I may be an off base... But I would has anyone gotten a DKP Essentials cluster up with these specs?
> 
> ```
> - 3 worker nodes
> - 8 CPU cores
>  - 16 GiB of RAM
>  - 60 GiB of Storage
> ```
> 
> all base commander functionality (monitoring, logging, backup, etc) plus Istio & kNative. Then lay Kaptain down on top of that? If that is just the base items, and no workload deployed, then we need to really call it out. @bruced2iq thoughts?

Sorry @dmennell.  I forgot to add the Kaptain instance deployed during tests was also used to run the [MNIST with MXNet](https://docs.d2iq.com/dkp/kaptain/2.0.0/tutorials/training/mxnet/) tutorial with no complications.

**Comment by cmastr** [comment]
We should not merge this until the testing can happen to tell us what needs to be in docs.

**Comment by cmastr** [comment]
Closing in favor of - https://jira.d2iq.com/browse/D2IQ-89293

**Pull request closed without merging**
