### PR TITLE
Konvoy docs latest - 1.5 and 1.6 Only

### PR DESCRIPTION
**Pull request by cmastr**
## Jira Ticket
Before creating this pull request, make sure you have a separate ticket for the docs team to track their work. If you need assistance, ask in the #documentation Slack channel.

## Checklist
- [ ] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [ ] Test all commands and procedures, if applicable.
- [ ] Create your PR against `staging`, not `master`. 
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> ie `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://wiki.d2iq.com/display/ENG/Contributing+to+Docs) for more information.

### CODE REVIEW

**Comment by cmastr** [comment]
RC1 not being published at this time.

**Comment by cmastr** [comment]
Need changes for just 1.5 and 1.6

**Comment by samvantran** [comment]
You'll want to revert 1.7 commits if we don't want to publish RC info yet

**Comment by cmastr** [comment]
We decided to just wait for GA.

**Pull request closed without merging**
