### PR TITLE
pn/DCOS_OSS-4072 - Update metrics for Telegraf

### PR DESCRIPTION
**Pull request by philipnrmn**
## Description
[DCOS_OSS-4072](https://jira.mesosphere.com/browse/DCOS_OSS-4072) - Audit documentation for metrics in 1.12

## Urgency
- [ ] Blocker 
- [x] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects).
- Change all affected versions (e.g. 1.7, 1.8, 1.9, 1.10, 1.11, 1.12).
- See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing).

### CODE REVIEW

**Comment by masonse** [comment]
I made some changes in the past 30min to the gDoc.  I'm not sure if they made it in.

**Comment by philipnrmn** [comment]
I pushed some changes on the differences between 1.11 and 1.12. 

Can I make changes to the release notes in 1.12 in this PR, or are they done separately?

**Comment by philipnrmn** [comment]
I added a section on differences to 1.11 and 1.12, which I will reference in the release notes for 1.12

**Comment by anithamuthu79** [comment]
@philipnrmn I've reviewed and edited the content on this PR for the recent updates. Shall we go ahead and merge this PR?

**Comment by masonse** [comment]
Looks good.

**Comment by philipnrmn** [comment]
LGTM, let's merge!

**Pull request merged**
