### PR TITLE
Patch Bump Updates Konvoy 1.8.4

### PR DESCRIPTION
**Pull request by mwrightd2**
## Jira Ticket

Before creating this pull request, make sure you have a separate ticket for the docs team to track their work. If you need assistance, ask in the #documentation Slack channel.

https://jira.d2iq.com/browse/D2IQ-82339

## Description of changes being made

Various versioning updates related to patch bump 1.8.4 based enclosed list:
https://github.com/mesosphere/konvoy/pull/3407/files?authenticity_token=ZyB3wUJzfmRzdeKpLxWeazbSeh7o5c0rLA9C0YG9CQrhtWi3iarjYDIphCf%2FOhFK12ZbooI2zgMXueOtxh2emA%3D%3D&file-filters%5B%5D=.md

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Create new PRs against `develop`, or `main` for hotfixes to production.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](./CONTRIBUTING.md) for more information.

### CODE REVIEW

**Review by cneth — COMMENTED** [review]
There are a bunch of 'testing' tags here and there in this PR, I believe those are wrong.   Please check with @joejulian before merging this.

**Comment by mwrightd2** [comment]
> There are a bunch of 'testing' tags here and there in this PR, I believe those are wrong. Please check with @joejulian before merging this.

Hey @cneth, thanks for your review! These testing tags appear all throughout: https://github.com/mesosphere/konvoy/pull/3407/files?authenticity_token=ZyB3wUJzfmRzdeKpLxWeazbSeh7o5c0rLA9C0YG9CQrhtWi3iarjYDIphCf%2FOhFK12ZbooI2zgMXueOtxh2emA%3D%3D&file-filters%5B%5D=.md

Are these tags meant for internal dev @joejulian?

**Review by cmastr — APPROVED** [review]

**Comment by dkoshkin** [comment]
Those tags were there for the RC, I've updated it to be the correct `stable` tags in the last commit.

**Comment by mwrightd2** [comment]
> @cneth @mwrightd2 Those tags were there for the RC, I've updated it to be the correct `stable` tags in the last commit.

Thanks @dkoshkin, ill update this file on my end.

**Review by cneth — APPROVED** [review]

**Review by cmastr — APPROVED** [review]

**Pull request merged**
