### PR TITLE
ss/COPS-5061 Adding info for uninstall script.

### PR DESCRIPTION
**Pull request by SarahStegall**
## Jira Ticket
https://jira.mesosphere.com/browse/COPS-5061
## Description of changes being made
In supported versions of DC/OS, (1.11-1.13), we now have a supported uninstall script publicly available here:

http://downloads.mesosphere.com/dcos-uninstall/uninstall.sh
The documentation should be updated to reflect this on all current and future versions of  DC/OS:
https://docs.mesosphere.com/1.12/installing/production/uninstalling/

Updated this page for versions:

- [x] 1.12
- [x] 1.13
- [x] 1.14

**I still need a step by step procedure for how to run this uninstall script.** Screenshots of feedback, such as CLI responses, would also be good.

### CODE REVIEW

**Comment by ck4adventure** [comment]
Adding do not merge as it seems this is WIP

**Comment by SarahStegall** [comment]
Requested review from Tony Windebank.

**Comment by SarahStegall** [comment]
Changes requested by Tony Windebank complete. Review requested.

**Comment by SarahStegall** [comment]
All three version changes passed multiple local builds.

**Pull request closed without merging**
