### PR TITLE
ci: changed runners labels

### PR DESCRIPTION
**Pull request by shaeed-noordeen**
## Description of changes being made

Added small runner label to workflows, if you have any queries regarding the size of the runners for any of the workflows please let the devprod team know asap.

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-<add_pr_##_here>.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

### CODE REVIEW

**Review by msdolbey — APPROVED** [review]
👍
Looks like it should be all good?
nice work

**Comment by cmastr** [comment]
Is 3 plus hours going to be the standard for this to run?
image

We need these PRs to build in like 15 minutes or less.

**Comment by hrantm** [comment]
> Is 3 plus hours going to be the standard for this to run? image
> 
> We need these PRs to build in like 15 minutes or less.

The job hasnt actually started, it hasent been picked up, you can look here. 
https://github.com/mesosphere/dcos-docs-site/actions/runs/3874934047/jobs/6606775629
@shaeed-noordeen is investigating an issue with the org wide runners being rolled out

**Comment by cmastr** [comment]
> > Is 3 plus hours going to be the standard for this to run? image
> > We need these PRs to build in like 15 minutes or less.
> 
> @cmastr The job hasn't actually started, it hasn't been picked up, you can look here. https://github.com/mesosphere/dcos-docs-site/actions/runs/3874934047/jobs/6606775629 @shaeed-noordeen is investigating an issue with the org wide runners being rolled out

Ok, gotcha! SGTM then. Also, phew glad it wouldn't be 3h. Would like for Russ to take a look at this PR before we merge.

**Review by vacas5 — APPROVED** [review]

**Comment by shaeed-noordeen** [comment]
As this is a public repo, we will not be able to add the labelled org-wide runners. So I am closing this pr. Public repos will need their own runners we will work on this and update you asap.

**Pull request closed without merging**
