### PR TITLE
1.10,1.11/installing/ent/upgrading: wait for cockroachdb underreplicated ranges

### PR DESCRIPTION
**Pull request by gpaul**
## Description
This PR updates the Upgrading documentation for 1.10 and 1.11 to specify that Dan must wait for the underreplicated_ranges value to drop to zero after a master was upgraded. 

@vishnu2kmohan do we have "master replacement" documentation somewhere or are these upgrade docs as close as we have?

Fixes https://jira.mesosphere.com/browse/DOCS-2458

## Urgency
- [ ] Blocker 
- [x] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects).
- Change all affected versions (e.g. 1.7, 1.8, 1.9, 1.10, 1.11).
- See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing).

### CODE REVIEW

**Comment by surdy** [comment]
@gpaul sadly we do not have Master replacement documentation (to the best of my knowledge). Enough customers do master replacement as a regular operation on DC/OS clusters that I think it warrants a docs page on it IMO.

**Comment by gpaul** [comment]
Here are screenshots of the tables for 1.10 and 1.11 using chrome on my laptop:
upgrade_1-10
upgrade_1-11

**Comment by gpaul** [comment]
> @gpaul sadly we do not have Master replacement documentation (to the best of my knowledge). Enough customers do master replacement as a regular operation on DC/OS clusters that I think it warrants a docs page on it IMO.

Given how sensitive the procedures are I'd very much like for us to have clear docs detailing the steps and have automated tests for those exact procedures. If a customer wants to do something even slightly different, we should write respond by telling them to hang on while we add a new test case for their scenario. 

I'm happy to take on this works and may pull info from you and others in #support-team if that's OK.

**Comment by jgehrcke** [comment]
Just noted the

>  **Tip:** If you are upgrading from permissive to strict mode, this URL will be `https://...`.

which was already there previously. How horribly wrong :(.

We should not advertise upgrading from permissive to strict, but more importantly: Exhibitor does not serve HTTPS

**Pull request merged**
