### PR TITLE
Lisa - Major Edge-LB Revision/Restructure

### PR DESCRIPTION
**Pull request by lsgunnlsgunn**
## Description

https://jira.mesosphere.com/browse/DCOS-43559
https://jira.mesosphere.com/browse/DCOS-26605
https://jira.mesosphere.com/browse/DCOS-47249
https://jira.mesosphere.com/browse/DCOS-50689
https://jira.mesosphere.com/browse/DCOS-50104
https://jira.mesosphere.com/browse/DCOS-47248
https://jira.mesosphere.com/browse/DCOS-49561
https://jira.mesosphere.com/browse/DCOS-47698
https://jira.mesosphere.com/browse/DCOS-43565

## Urgency
- [ ] Blocker 
- [ ] High
- [x] Medium

## Requirements
- Test all commands and procedures.
- Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects).
- Change all affected versions (e.g. 1.7, 1.8, 1.9, 1.10, 1.11, 1.12).
- See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing).

### CODE REVIEW

**Comment by lsgunnlsgunn** [comment]
Here is the current snapshot of the Edge-LB single layer (not broken out into multiple docs organized by version. It is still rough around the edges (no pun intended), and for a future pass the remaining samples should all be converted into tasks with steps.

**Comment by niartenyaw** [comment]
@lsgunnlsgunn before merging, can you revert (or remove) the last two commits (`440a996` and `9f818d6`) that are editing the `docker-compose` and `Dockerfile.docs` files?

**Comment by lsgunnlsgunn** [comment]
@niartenyaw, I reverted the last two commits (440a996 and 9f818d6) that are editing the docker-compose and Dockerfile.docs files.

**Comment by lsgunnlsgunn** [comment]
Too many changes got bundled into this PR, so I'm closing it. The replacement PR is 
https://github.com/mesosphere/dcos-docs-site/pull/2163
merged without conflicts

**Pull request closed without merging**
