### PR TITLE
universal installer 0.2

### PR DESCRIPTION
**Pull request by fatz**
## Description
https://jira.mesosphere.com/browse/DCOS_OSS-5043

## Urgency
- [ ] Blocker 
- [x] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects).
- Change all affected versions (e.g. 1.7, 1.8, 1.9, 1.10, 1.11, 1.12).
- See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing).

### CODE REVIEW

**Comment by fatz** [comment]
@niartenyaw can you have a closer look at this PR. IMO there is a problem with the copy plugin and the new prism version

**Comment by niartenyaw** [comment]
@fatz oh I do see the issue with the copy button now. Feels weird that it changed due to changing prism, I'll take a closer look at this.

**Comment by fatz** [comment]
@niartenyaw would be great if we can get this through somehow. I'm out for a while now. 

If the prism issue is unsolvable please merge without

Adding @victhar @bernadinm @geekbass

**Comment by niartenyaw** [comment]
@fatz i won't be able to debug this today, but i can take a look Monday afternoon. if you need this in asap, let's move the prism update to a different PR. thanks!

**Comment by ck4adventure** [comment]
@fatz Is there a docs ticket for this already?? This feature is actually on my list of things to shepherd for the release, and we've been sprinting accordingly. We need the appropriate docs tickets to review this, and also, we need to know, is this 1.12 only? 1.13 release?? Does it backport to 1.10 and 1.11 and need those pages added too?

Also, please do shift the prism content to a separate PR so Aaron our engineer can track that work separately. 

Thanks!!

**Comment by ck4adventure** [comment]
Adding do not merge label until I can get a pass in to get these ready for the docs.

**Comment by sebbrandt87** [comment]
@ck4adventure jira issue created
Removed prism update out of this PR.
We currently just want to add the docs for 1.12 and the new universal installer version here.

**Comment by ck4adventure** [comment]
Pulled this into the docs repo as a branch for language and formatting edits, please see pull #2169.

**Pull request closed without merging**
