### PR TITLE
Modify custom CA instructions for certificate renewal

### PR DESCRIPTION
**Pull request by jongiddy**
## Jira Ticket

https://jira.d2iq.com/browse/D2IQ-71528

## Description of changes being made

Rewrite custom certificate page to add support for certificate renewal.

Although this will also work in the next minor versions of 2.1 and 2.0, I am just changing 2.2 for now to support the beta release. Once we're happy with 2.2 beta results and perhaps closer to minor updates to earlier versions, I will copy this back to 2.1 and 2.0

## Checklist
- [ ] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [x] Test all commands and procedures, if applicable.
- [x] Create your PR against `staging`, not `master`. 
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> ie `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://wiki.d2iq.com/display/ENG/Contributing+to+Docs) for more information.

### CODE REVIEW

**Review by cneth — CHANGES_REQUESTED** [review]
Thanks for cleaning up the terminology on this page.  

However, I am not sure I understand how you 'replace' an existing cert.  Do you just reinstall like a 'patch' upgrade?   I assume there must be some restrictions on what you can change when you do this?   

It would be great if we had a 'worked example' for this procedure.

**Comment by jongiddy** [comment]
@cneth Thanks for the comments.

Previously, we only permitted custom CA's during installation, and if they expired or were compromised they could only be changed by cluster reinstallation. Now we allow the CA certificate and key to be changed during installation, a version upgrade, or a patch upgrade. This changes the CA certificate on all nodes and replaces all the service certificates.

There's a few cases:
1. setup custom certificate during installation
2. add a custom certificate during a patch upgrade
3. replace an existing custom certificate with a new one during a patch upgrade ("cert renewal")
4. remove the custom certificate during a patch upgrade

I've currently just used one section for all 4 cases, but maybe I should separate them out.

From an implementation POV, case 2 is the same as case 3, but replacing the default CA with a custom cert. Case 4 is also the same as case 3 but replacing a custom cert with the default CA.

From a user perspective, case 1 and 2 both make the cluster use a CA selected by the user, for example, because the org wants to only use its certs. Case 3 provides "certificate renewal", although case 2 is also certificate renewal if you previously chose the default CA. Case 4 is an unlikely user requirement, so we could probably leave it undocumented (or mention it as an aside).

Do you think it would be clearer if I replaced the `Install or patch DC/OS` section with two sections?
- `Setting the CA certificate` (with a comment that not setting the attributes uses a default CA)
- `Renewing the CA certificate` (with a comment that unsetting the attributes reverts to the default CA)

**Comment by cneth** [comment]
> Do you think it would be clearer if I replaced the `Install or patch DC/OS` section with two sections?
> 
> * `Setting the CA certificate` (with a comment that not setting the attributes uses a default CA)
> * `Renewing the CA certificate` (with a comment that unsetting the attributes reverts to the default CA)

Yes, I think this is a great idea, as those are the two main reasons you'd be referring to these docs.

**Comment by cmastr** [comment]
going to start merging this. If any outstanding comments, open a new PR to address.

**Review by cmastr — APPROVED** [review]

**Review by cmastr — APPROVED** [review]

**Comment by jongiddy** [comment]
Split into two sections described above will be done in https://jira.d2iq.com/browse/D2IQ-71896

**Pull request merged**
