### PR TITLE
[Doc][Kommander]Updated menu weights for Kommander.

### PR DESCRIPTION
**Pull request by russurquhart1**
## Jira Ticket
Before creating this pull request, make sure you have a separate ticket for the docs team to track their work. If you need assistance, ask in the #documentation Slack channel.

## Description of changes being made
Fixed ordering of Release Note items.

## Checklist
- [ ] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [ ] Test all commands and procedures, if applicable.
- [ ] Create your PR against `main`. 
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://wiki.d2iq.com/display/ENG/Contributing+to+Docs) for more information.

### CODE REVIEW

**Review by gracedo — APPROVED** [review]

**Review by samvantran — COMMENTED** [review]
Heyooo 🙌  nice one @russurquhart1! Can you also update 1.2 release notes bc the same problem exists

**Review by gracedo — COMMENTED** [review]
Oh wait you need to update for kommander 1.2 RN as well

**Comment by russurquhart1** [comment]
Updated the RN's for 1.2 as well. @pierrebeitz said we might have been able to circumvent this by having `1.2.0` for the name of the directory rather than `1.2`. Same for `1.3`. that could account for the default sorting error. Explicitly setting the menuweights also fixes this and is probably more correct. fwiw.

**Comment by pierrebeitz** [comment]
I was about not having two menu-entries highlighted at the same time. See @gracedo 's Screenshot in slack.

**Comment by russurquhart1** [comment]
@pierrebeitz Let me know if this is what you meant, in my last commit.

**Pull request merged**
