### PR TITLE
Add dse 6.0.1

### PR DESCRIPTION
**Pull request by niartenyaw**
https://jira.mesosphere.com/browse/DCOS-42786

- [ ] Blocker 
- [ ] High
- [ ] Medium

- Test all commands and procedures.
- Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects).
- Change all affected versions (e.g. 1.7, 1.8, 1.9, 1.10, 1.11, 1.12).
- See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing).

### CODE REVIEW

**Comment by niartenyaw** [comment]
DSE 6.0.1 has been removed. This PR is ready for when it becomes available @ryadav88

**Comment by ryadav88** [comment]
@vishnu2kmohan just fyi ^

**Comment by ck4adventure** [comment]
@niartenyaw Can this be closed at this point??

**Comment by niartenyaw** [comment]
i would think so since we'v already released 6.7.2. @ryadav88 ?

**Comment by ryadav88** [comment]
Ya this can now be closed.

**Pull request closed without merging**
