### PR TITLE
fix: remove vsphere centos7 support

### PR DESCRIPTION
**Pull request by faiq**
## Jira Ticket

closes - https://jira.d2iq.com/browse/D2IQ-91902 

## Description of changes being made
 
According to https://jira.d2iq.com/browse/D2IQ-89269 we do not have this feature yet. So removing it from our list

### Preview

You can preview the docs build using the following URL, adding the PR # where specified:
http://docs-d2iq-com-pr-<add_pr_##_here>.s3-website-us-west-2.amazonaws.com/

## Checklist

- [ ] Test all commands and procedures, if applicable.
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/blob/main/CONTRIBUTING.md) for more information.

### CODE REVIEW

**Review by mmcelroy91 — APPROVED** [review]

**Comment by mmcelroy91** [comment]
Also fixed in Confluence on Supported Operating systems under vSphere table https://d2iq.atlassian.net/wiki/spaces/DENT/pages/29917260/Supported+Infrastructure+Operating+Systems

**Review by cmastr — CHANGES_REQUESTED** [review]
I want QA to approve this.

**Comment by mmcelroy91** [comment]
According to the OS/Provider Support Matrices sheet, CentOS was in fact NOT supported by vSphere, so I had already gone into 2.3 and deleted it from the table.  I will add it back if Support says so. https://docs.google.com/spreadsheets/d/1pIaseCIbDtN5hI7Qn05aQONMiSWjGTs2BWywzBkbYSk/edit#gid=1513714469

**Review by supershal — APPROVED** [review]
we have not implemented it in KIB yet as this feature was descoped for 2.3

**Review by cmastr — APPROVED** [review]

**Review by cneth — APPROVED** [review]

**Comment by mmcelroy91** [comment]
I think since we had a giant Slack chain about this and verified CentOS removal, plus Craig approved, we can let Kevin off the hook due to GA responsibilities for him.  So I am merging.

**Review by kevinmiller-conley — COMMENTED** [review]
Fell a little behind on emails, but LGTM 😅

**Pull request merged**
