### PR TITLE
making links a bit more md friendly per sams feedback for kommander-i…

### PR DESCRIPTION
**Pull request by msdolbey**
…nstall-airgapped

## Jira Ticket
N/A

## Description of changes being made
Per feedback from @samba - just making these internal links more markdown friendly, also having them be internal links.

## Checklist
- [ ] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [ ] Test all commands and procedures, if applicable.
- [ ] Create your PR against `staging`, not `master`. 
- [ ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> ie `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://wiki.d2iq.com/display/ENG/Contributing+to+Docs) for more information.

### CODE REVIEW

**Review by makkes — CHANGES_REQUESTED** [review]
I'm not sure I understand the motivation here. My personal take is that I don't like this way of linking somewhere because as an editor I'd have to jump back and forth to see where the link goes to or to add new links. This makes link addition/removal/editing a tedious process, whereas the `[text](URL)` way of linking is self-contained and easily editable without having to jump back and forth in the document.

**Comment by msdolbey** [comment]
> I'm not sure I understand the motivation here. My personal take is that I don't like this way of linking somewhere because as an editor I'd have to jump back and forth to see where the link goes to or to add new links. This makes link addition/removal/editing a tedious process, whereas the `[text](URL)` way of linking is self-contained and easily editable without having to jump back and forth in the document.

I'm a bit ambivalent to this as well, but I think it's something that we can try to be consistent on. Either way, if this doesn't get in or not, just responding to feedback. 

That being said, if we don't want to do it this way, we should probably keep the internal linky part. 

I'll let @russurquhart1 @cmastr decide what they would rather have.

**Review by russurquhart1 — COMMENTED** [review]
I think this method is a more neat method, and is optimal if certain links get used a lot in a doc.

**Review by makkes — APPROVED** [review]
I'll bow to the majority.

**Comment by cmastr** [comment]
I do like this model better. We are not using it anywhere but Konvoy atm. This is a good start, and we need to make sure to communicate that we are moving to this type of link structure in Kommander.

**Review by cmastr — APPROVED** [review]

**Pull request merged**
