### PR TITLE
Make docker great again

### PR DESCRIPTION
**Pull request by niartenyaw**
## Description
Their docker setup was ridiculous so i fixed it.

1. Add a `.env` file with `ENV=development` in it (can also use `production` for a full build). 

2. Then build the container:
```
docker-compose build web
```
3. Run the container:
```
docker-compose up web
```

Then go to `localhost` and test that any bad link will redirect back down to the nearest node.

When done shut down container:
```
docker-compose down web
```

## Urgency
- [ ] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects).
- Change all affected versions (e.g. 1.7, 1.8, 1.9, 1.10, 1.11, 1.12).
- See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing).

### CODE REVIEW

**Comment by ck4adventure** [comment]
Does this need more testing?????

**Comment by niartenyaw** [comment]
Prob want to push it to `develop` to make sure it doesn't break the CI, but other than that as long as you have checked it works

**Comment by ck4adventure** [comment]
then yes, I will do more to check this out

**Comment by niartenyaw** [comment]
this seems to be working on review, can we merge @ck4adventure ?

**Pull request merged**
