### PR TITLE
feat: new service landing page

### PR DESCRIPTION
**Pull request by niartenyaw**
## Jira Ticket
Before creating this pull request, please make sure you have a separate ticket for the docs team to track their work to review and merge, even for minor edits. If you need assistance, ask in the #doc-team channel on slack.

## Checklist
- [ ] Make sure you change all affected versions (e.g. 1.10, 1.11, 1.12, 1.13).
- [ ] Test all commands and procedures where applicable.
- [ ] Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects) if you are moving a page.

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing) for more information.

### CODE REVIEW

**Comment by jdef** [comment]
any reason that this new header is just added to the landing page, vs all the pages for the service?

**Comment by niartenyaw** [comment]
hey @jdef ! yeah, this new header is being used to reorganize the services landing page by categories. that landing page looks at the top level page per service for organization (and no other pages) so it'll be easiest to maintain that header if it's only on the top level page.

excited to see what you think when it's done!

**Comment by jdef** [comment]
@niartenyaw can I go ahead and add the new category header to the upstream storage docs (a) w/o fear of breaking anything before this feature lands, and; (b) with confidence that this feature will land ?

**Comment by niartenyaw** [comment]
@jdef thanks for staying ahead of the game. we haven't gotten the category breakdown approved yet, but once that happens we can let you know. waiting for initial dev to be done so people can see it live. in any case, adding it early shouldn't break anything and i don't see there being an issue with a `Storage` category.

**Pull request merged**
