### PR TITLE
[DCOS-59963] [Elastic] Remove mention of unsupported X-Pack authz and authn

### PR DESCRIPTION
**Pull request by phrynchanka**
## Jira Ticket
https://jira.mesosphere.com/browse/DCOS-59963
https://jira.mesosphere.com/browse/DCOS-58552
## Description of changes being made
[Elastic] Remove mention of unsupported X-Pack authz and authn
[Elastic] Document DC/OS 1.11 Kibana Admin router integration limitation
## Checklist
- [x] Make sure you change all affected versions (e.g. 1.10, 1.11, 1.12, 1.13).
- [x] Test all commands and procedures where applicable.

### CODE REVIEW

**Comment by SarahStegall** [comment]
Do not merge until PR2527 has been merged.

**Comment by mpereira** [comment]
> Do not merge until PR2527 has been merged.
Why?

**Comment by samvantran** [comment]
Sidenote @SarahStegall if you add a `#` in front of the number you can link directly to the PR 
ie PR #2527

**Comment by cmastr** [comment]
> > Do not merge until PR2527 has been merged.
> 
> Why?

I'm assuming it's because it'll cause merge conflicts if we don't.

**Pull request merged**
