### PR TITLE
Add Kaptain 2.0.0 docs as a subtree

### PR DESCRIPTION
**Pull request by timcharper**
## Jira Ticket

[D2IQ-85624](https://jira.d2iq.com/browse/D2IQ-85624)

## Description of changes being made

Kaptain 2.0.0 docs are brought in to the dcos-docs-site via a git subtree. Git subtrees can be used to push and pull documentation either the Kaptain repository or dcos-docs-site repository and synchronize bidirectionally.

### CODE REVIEW

**Comment by alembiewski** [comment]
Note for the reviewers: the changes you see in the PR are not new, we are just copying docs from the previous release (1.3.0). Also, is there a way to merge these changes without making them be visible at the docs site? This way we can start working on docs for Kaptain 2.0

**Comment by gvasquezvargas** [comment]
Thanks @alembiewski! Regarding your question above, @vacas5 might be able to provide some info. He found a way to keep whole folders/parts of the repo hidden before a release. (For example, all of our docs are being implemented in `main`, but everything will remain hidden until GA)

**Review by vacas5 — APPROVED** [review]

**Comment by timcharper** [comment]
The documentation will be primarily maintained in this repo, dcos-docs-site. Kaptain has some documentation that is managed by tutorial notebooks which are also used in our testing suite, so those tutorial notebooks must reside in the Kaptain repository. There is a comment at the top of each page that "this is auto generated". Further, SDK API docs are generated from our Python code.

Doc writers will not need to learn anything new with the subtree as we (devs) will be running the subtree push/pull after we update generated documentation, they can mostly ignore that we are doing this and just edit pages as normal.

**Comment by juliangieseke** [comment]
Ah ok.. well thank you GH UI.. (I did not close it, but its the same as #4306 now lol)

**Pull request closed without merging**
