### PR TITLE
Add guidance that customers should not set `bouncer_expiration_auth_t…

### PR DESCRIPTION
**Pull request by adamtheturtle**
…oken_days` to less than 0.25 days

## Description

* https://jira.mesosphere.com/browse/DCOS-40561
* https://jira.mesosphere.com/browse/COPS-2836

## Urgency
- [ ] Blocker 
- [ ] High
- [X] Medium

## Requirements
- Test all commands and procedures.
- Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects).
- Change all affected versions (e.g. 1.7, 1.8, 1.9, 1.10, 1.11).
- See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing).

### CODE REVIEW

**Comment by adamtheturtle** [comment]
@ifraser1966 @adyatlov - are you aware of any customers using lower values than 0.25 for this configuration parameter? What are their workloads like?

**Comment by adyatlov** [comment]
Thanks, @adamtheturtle!

**Comment by adamtheturtle** [comment]
Let's give @jgehrcke an opportunity to review this as he has considered this deeply.

**Comment by ifraser1966** [comment]
Hi,
Visa is the only one of my customers doing 0.25, which is the lowest we would recommend - they tested their workloads (not huge, simple apps, small cluster too) and found no issues.

**Comment by adyatlov** [comment]
Let's add this paragraph to the pages/1.10/installing/oss/custom/configuration/configuration-parameters/index.md as well.

**Comment by adamtheturtle** [comment]
> Let's add this paragraph to the pages/1.10/installing/oss/custom/configuration/configuration-parameters/index.md as well.

There is no relevant section there.

> Once we have thorough internal testing for a value of 1 hour we can update the docs again.

😄

**Comment by adamtheturtle** [comment]
cc @jpe442 @SarahStegall @anithamuthu79 please can someone merge this?

**Pull request merged**
