### PR TITLE
storage: update storage doc for 1.0.0

### PR DESCRIPTION
**Pull request by jdef**
https://jira.mesosphere.com/browse/DCOS-53630

## Description of changes being made

* docs for the DC/OS Storage Service v1.0 release
* many changes have already been reviewed by @lsgunnlsgunn 
* see patch file attached to JIRA ticket for easy comparison between v0.6.0 and v1.0.0 docs
  - https://jira.mesosphere.com/secure/attachment/62712/storage-v0_6_0-v1_0_0rc1.patch

## Checklist
- [x] Make sure you change all affected versions (e.g. 1.10, 1.11, 1.12, 1.13).
  - n/a
- [ ] Test all commands and procedures where applicable.
- [ ] Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects) if you are moving a page.

See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing) for more information.

### CODE REVIEW

**Comment by SarahStegall** [comment]
Adding Do Not Merge label because 13.2 release is not yet ready.

**Comment by jdef** [comment]
heads up - we're planning to launch DSS on July 8th. we're going to be cutting an RC2 today that will push some additional (already-reviewed) changes to this PR.

**Comment by jdef** [comment]
Reminder: please do not directly edit the PRs generated by storage automation (basically the "storage_x_y_z" branches) because they may be blindly overwritten by the automation scripts.

**Comment by jdef** [comment]
picked e3109e4 edits from @lsgunnlsgunn into DSS 1.0.x release branch:

https://github.com/mesosphere/dcos-storage/commit/5a2f80e9f77a912d5c502b3f7a529c795eebfcfa

**Comment by lsgunnlsgunn** [comment]
Sorry, my bad--didn't realize it.

**Comment by jdef** [comment]
> Sorry, my bad--didn't realize it.

No worries @lsgunnlsgunn . Since I noticed what happened, I already picked you changes upstream and the next build of the DSS release branch (in progress right now) should force-push to this branch w/ your latest edits.

**Comment by ck4adventure** [comment]
I pushed up an index file was missing - should be a one time add and done since it is above the version level that would normally get pushed over by the dss repo.

**Comment by jdef** [comment]
> I pushed up an index file was missing - should be a one time add and done since it is above the version level that would normally get pushed over by the dss repo.

@ck4adventure Thanks for the heads up. This still might be overwritten by a force-push the next time a DSS v1.0.0 RC/snapshot/release is built. Might be better off creating this top-level index file in a separate PR that's not controlled by a robot.

**Comment by jdef** [comment]
@ck4adventure it looks like your splash page addition was wiped out by the robot. instead of committing to this PR, can you open another PR that includes that change?

**Comment by jdef** [comment]
removed "do not merge" label since 1.13.2 just shipped

**Pull request merged**
