### PR TITLE
storage: update storage doc for 0.6.0

### PR DESCRIPTION
**Pull request by jdef**
## Description
https://jira.mesosphere.com/browse/DCOS-53424

## Urgency
- [ ] Blocker 
- [x] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects).
- Change all affected versions (e.g. 1.7, 1.8, 1.9, 1.10, 1.11, 1.12).
- See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing).

### CODE REVIEW

**Comment by jdef** [comment]
hrm, just realized that we forgot to include upgrade notes for 0.6.x

**Comment by jpe442** [comment]
the diff you attached @jdef LGTM, you are just going to add the upgrade notes?

**Comment by jpe442** [comment]
@jdef also, yes, the diff file you attached was helpful to see what changed faster. Thanks!

**Comment by jdef** [comment]
> the diff you attached @jdef LGTM, you are just going to add the upgrade notes?

Yes, I'm going to update the branch w/ upgrade notes.

**Comment by jdef** [comment]
updated release notes here: https://github.com/mesosphere/dcos-storage/pull/461

**Comment by jdef** [comment]
updated docs pushed, PTAL

**Comment by jpe442** [comment]
LGTM

**Pull request merged**
