### PR TITLE
Update package-manager.yaml

### PR DESCRIPTION
**Pull request by larioj**
## Urgency
- [x] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects).
- Change all affected versions (e.g. 1.7, 1.8, 1.9, 1.10, 1.11).
- See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing).

### CODE REVIEW

**Comment by larioj** [comment]
I tested these changes using swagger editor

**Comment by larioj** [comment]
To view changes, go to https://editor.swagger.io/ and `File->import url` and pass in the url of the swagger file you are interested in. You can get the url by going to `Files Changed -> View -> Raw` and the copy get the url from the url bar.

**Comment by takirala** [comment]
`/package/resource` endpoint is missing (or am I looking the wrong file?) in `1.11` file. Is this intentional? (As we used to have it in docs earlier E.g.: https://teamcity.mesosphere.io/repository/download/DcosIo_Cosmos_PublishRelease/944404:id/cosmos.html)

**Comment by larioj** [comment]
@pavisandhu I tested this by running the docs site locally. Everything looks good

**Pull request merged**
