### PR TITLE
Networking doc re-org, introducing `dcos-net` and IPv6 for docker containers.

### PR DESCRIPTION
**Pull request by asridharan**
## Urgency
- [x] Blocker 
- [ ] High
- [ ] Medium

## Requirements
- Test all commands and procedures.
- Add [redirects](https://github.com/mesosphere/dcos-docs-site/wiki/Redirects).
- Change all affected versions (e.g. 1.7, 1.8, 1.9, 1.10, 1.11).
- See the [contribution guidelines](https://github.com/mesosphere/dcos-docs-site/wiki/Contributing).

---
This change is [Reviewable](https://reviewable.io/reviews/mesosphere/dcos-docs-site/475)

### CODE REVIEW

**Comment by asridharan** [comment]
@GoelDeepak @urbanserj @pavisandhu could you review this. This includes some changes to the organization structure of the docs. Re-write of the DNS section to better explain the various FQDN we use. Re-write of the networking introduction to better highlight the different networking modes. A re-org of the "Virtual Network" section and re-naming of this section "Software Defined Networks" .  

Have also introduced `dcos-net`

Will be adding a few more commits to introduce IPv6 for docker containers on DC/OS overlay.

**Comment by urbanserj** [comment]
@asridharan could you please rebase your branch with master to resolve the merge conflicts?

**Comment by asridharan** [comment]
@urbanserj will do.

**Comment by asridharan** [comment]
closing this in favor of #478

**Pull request closed without merging**
