### PR TITLE
docs: update iam policy for kommander

### PR DESCRIPTION
**Pull request by some-things**
## Jira Ticket
Before creating this pull request, make sure you have a separate ticket for the docs team to track their work. If you need assistance, ask in the #documentation Slack channel.

https://jira.d2iq.com/browse/COPS-6903

## Description of changes being made
Update Kommander IAM policy

## Checklist
- [ x ] Change all affected versions, if applicable (e.g. 1.13, 2.0, 2.1).
- [  ] Test all commands and procedures, if applicable.
- [ x ] Create your PR against `main`. 
- [  ] Update all links if you are moving a page.
- [ ] Add release date to Release Notes page in the following format: <Package> was released on <Day>, <Month> <Year> Example: `Mesosphere® DC/OS™ 2.1.0 was released on 9, June 2020`

See the [contribution guidelines](https://wiki.d2iq.com/display/ENG/Contributing+to+Docs) for more information.

### CODE REVIEW

**Comment by some-things** [comment]
Missed updating the static creds section which passes the iam policy: https://docs.d2iq.com/dkp/kommander/1.4/operations/infrastructure-providers/configure-aws-infrastructure-provider-static-credentials/

Fixing this now.

**Comment by some-things** [comment]
Added commit for updating the create-policy command.

This PR is ready for review.

**Review by cneth — CHANGES_REQUESTED** [review]
This LGTM, but Casie mentioned that the Kommander docs now live in Kommander repo, so need to make sure we make this edit in the right place so it doesn't get overwritten by the automation....

**Comment by cmastr** [comment]
> This LGTM, but Casie mentioned that the Kommander docs now live in Kommander repo, so need to make sure we make this edit in the right place so it doesn't get overwritten by the automation....

Dustin and I talked about this. Kommander in Kommander repo is for 2.0 and above. This is good the way it is for now.

**Review by msdolbey — APPROVED** [review]
👍 
All about the policies

**Review by samvantran — APPROVED** [review]

**Pull request merged**
