### PR TITLE
Update configuration json in NiFi

### PR DESCRIPTION
**Pull request by Gupta-Amrit**
## Jira Ticket
https://jira.mesosphere.com/browse/DCOS-57156

## Description of changes being made
Updating configuration json file for edgelb and custom installation.

### CODE REVIEW

**Comment by ck4adventure** [comment]
Hi there, @Gupta-Amrit , I can't seem to pull this branch to be able to check it before approving merging, please allow access, thanks.

**Comment by Gupta-Amrit** [comment]
> Hi there, @Gupta-Amrit , I can't seem to pull this branch to be able to check it before approving merging, please allow access, thanks.

Hi @ck4adventure , 
Invitation link: https://github.com/Gupta-Amrit/dcos-docs-site/invitations

**Comment by ck4adventure** [comment]
> Hi @ck4adventure ,
> Invitation link: https://github.com/Gupta-Amrit/dcos-docs-site/invitations

Thank you, at first glance, I think I spotted a few last spots where there was {{ model.servicename}} in the code blocks, those all do need to get changed to `nifi` (or whatever text value they are referencing), our parser skips code blocks, far as I know.

Same goes for any backtics in html code blocks (Notes and Warnings), as they are html, the parser skips over any addtl interpolation, so they need to be replaced with <code></code> in order to get that format change to display.

**Comment by Gupta-Amrit** [comment]
> {{ model.servicename}}

I checked by locally building it and found out that it is rendering/parsing {{model.serviceName}} to nifi. Do I still need to change?

**Comment by Gupta-Amrit** [comment]
> Same goes for any backtics in html code blocks (Notes and Warnings), as they are html, the parser skips over any addtl interpolation, so they need to be replaced with in order to get that format change to display.

Done

**Pull request closed without merging**
